/* GENERATED by pipeline/wrap_blocks.py from hairlab/blocks/gaze.js.
   Do not edit here and do not edit the block below: the owning
   session's copy is the source of truth and this file is that source
   wrapped, unchanged. Re-run the script instead. */

export function install(H){
  const { THREE, bone, charRoot, camera, rotateBoneWorld, IDENT, addActions, addBase } = H;
  let current = null;
  let faceTrigger, faceHoldBias, faceGazeBias, twistGazeBias, FACE;

/* ══════ verbatim: hairlab/blocks/gaze.js ══════ */
/* gaze.js — extracted from hairlab/index.html by extract_blocks.py.
   Do not edit here; edit index.html and re-run the extractor. */

/* ══ BEGIN PORTABLE BLOCK: gaze ══════════════════════════════════════════════
   ─────────────────── gaze ───────────────────────────────────────────────────
   ── LIFT-OUT NOTE ─────────────────────────────────────────────────────────
   Self-contained on purpose, so it can be moved into the other builds. It needs
   six things from its host: bone(name), rotateBoneWorld(b, qWorld), IDENT,
   charRoot, camera, and addActions + addBase if you want the look-around
   overlay ducked (optional; it no-ops without them). It also glances at a
   `current` action for the per-clip veto, guarded in try/catch, so a host
   without one is unaffected. Call setupGaze() once after the bones are mapped,
   and applyGaze(dt) in slot three — after the animation and the grab, before
   the physics, because the hair and the soft tissue both read what it writes.
   ──────────────────────────────────────────────────────────────────────────

   She knows where you are; she does not stare at you. She looks over, holds it,
   looks away, comes back. Orbit far enough behind her shoulder that meeting
   your eye would mean wringing her neck and she gives up rather than straining
   — faces front and goes back to idling until you are visible again.

   WHY IT IS BUILT THIS WAY. The first version tracked the camera continuously
   through a first-order lag and Luca's verdict was "creepy, like a robot". Both
   halves of that were right and they are different bugs.

   · A first-order lag moves FASTEST at the instant it starts and creeps at the
     end. That is a servo seeking a setpoint. Every head turn here is now a
     second-order spring: it starts at zero velocity, accelerates, and settles.
     Slightly under-damped, so it arrives with a whisper of overshoot instead of
     asymptotically, which is what a neck does.
   · Continuous tracking means she re-aims on every pixel the camera moves, and
     nothing in a person works that way. She now commits to a target and keeps
     it. A new one is only taken up if you have drifted past `reacquire` AND she
     has held the old one for `reacquireWait` — and then only after a reaction
     beat. Between those, she is looking where she decided to look, which is
     what "knows where you are" actually looks like from the outside.

   Her eyes commit at the moment of the decision and her head follows after the
   beat, so the eyes lead — people point their eyes first and bring the head
   after. And the turn is spread from her abdomen up: past about 20° the torso
   starts taking a share, so a big look is her whole body coming round rather
   than a skull rotating on a fixed body. That, and the reaction beat, are the
   two things that stop it reading as a machine noticing you.

   STILL MISSING, and it needs animation rather than code: a standing idle that
   is authored to be turned out of, plus real body language — a weight shift
   onto the other foot, an arm touched, a glance back over the shoulder. Spec
   is in the project notes for whoever owns poses/.                           */
const GAZE = {
  on: true,
  yawMax: 73, pitchUp: 26, pitchDown: 30,   // how far she will comfortably go
  giveUp: 84,        // past this she stops trying to meet your eye
  regain: 62,        // and re-engages only inside this — hysteresis, or she
                     // flickers in and out every time you hover at the boundary
  /* 13° is Luca's, and it is a deliberate retreat from the 34° I had: at this
     range her eyes barely leave centre and essentially travel with her head, so
     the "eyes arrive first" read is mostly gone. What replaces it is the
     look-around overlay, which he left running at 0.55 and only ducked by 0.37 —
     so the small darts now come from the animation and the deliberate turns come
     from here. That division is cleaner than what I built. */
  eyeYaw: 13, eyePitch: 20,
  /* Motion. `ease` is a natural frequency in rad/s: 3.2 settles in about 1.4 s.
     Raising it does not make her "snappier" so much as younger and more alert;
     dropping it reads sleepy. */
  ease: 2.15,            // ~2.1 s for a look to land. He slowed it by a third again
  damp: 1.15,            // and took the overshoot out entirely: over-damped, it arrives and stops
  react: [0.455, 1.365], // the beat before she starts to move — nearly a second at the middle
  eyeSpeed: 8,
  /* 44° with a 0.2 s wait is the opposite trade from mine and it is better: she
     almost never bothers re-looking for a small move, but when you genuinely go
     somewhere else she does not sit on a timer first. */
  reacquire: 44,
  reacquireWait: 0.2,
  torso: 1.86, torsoFrom: 18, torsoSpan: 46,   // nearly double the body participation
  weightSpeed: 1.8,
  holdCam: [4.5, 10.5],     // seconds spent looking at you — long
  holdAway: [3.355, 8.845], // and elsewhere
  awayMin: 24, awayMax: 58,
  suppress: 0.37,        // how much of the look-around overlay to duck while engaged
  express: true,         // fire a facial expression when she lands on you
  /* Per-clip scale on the whole behaviour. Asleep she should not track you at
     all — the clip sweep caught her holding 62° of eye contact through
     Idle_Sleep, which is worse than having no gaze system. A pose can make a
     behaviour wrong even when the behaviour is right. */
  byClip: { Idle_Sleep: 0, Idle_LieProp: 0.55 },
};
/* The chain, base first. The torso shares are scaled by how far she has to go;
   the head takes whatever is left so the aim lands exactly however the rest is
   distributed. A 50° turn taken entirely at the skull is an owl. */
const GAZE_NECK = [['neckLower', 0.20], ['neckUpper', 0.42], ['head', 1.0]];
const GAZE_TORSO = [['abdomenUpper', 0.10], ['chestLower', 0.22], ['chestUpper', 0.26]];
/* Measured against her PELVIS, not her chest. The chest is a link this system
   rotates, so measuring in the chest frame would feed its own output back into
   its input and the turn would settle somewhere short, or hunt. */
const GAZE_REF = 'abdomenLower';
const gazeState = {
  ready: false, mode: 'idle', sub: 'cam', t: 0, weight: 0,
  curYaw: 0, curPitch: 0, velYaw: 0, velPitch: 0,
  aimYaw: 0, aimPitch: 0, pendYaw: 0, pendPitch: 0, pending: false, reactT: 0,
  heldFor: 0, eyeYaw: 0, eyePitch: 0, camYaw: 0, camPitch: 0, arrived: false,
  awayYaw: 0, awayPitch: 0,
  bones: [], anim: [], eyeAxisOk: null,
};
/* Own scratch. Every helper copies before it writes, for the reason §4 of the
   handoff gives: sharing a temporary between a caller and its callee is what
   turned the elbow aim into a silent no-op for weeks. */
const _gP = new THREE.Vector3(), _gD = new THREE.Vector3(), _gL = new THREE.Vector3();
const _gF = new THREE.Vector3(), _gE = new THREE.Vector3();
const _gQc = new THREE.Quaternion(), _gQi = new THREE.Quaternion();
const _gQh = new THREE.Quaternion(), _gQd = new THREE.Quaternion();
const _gQb = new THREE.Quaternion(), _gQe = new THREE.Quaternion();
const D2R = Math.PI / 180, R2D = 180 / Math.PI;
const gClamp = (v, lo, hi) => v < lo ? lo : (v > hi ? hi : v);
const gRand = (a, b) => a + Math.random() * (b - a);

function gazeDir(yawDeg, pitchDeg, q, out){
  const y = yawDeg * D2R, p = pitchDeg * D2R, cp = Math.cos(p);
  return out.set(Math.sin(y) * cp, Math.sin(p), Math.cos(y) * cp).applyQuaternion(q);
}
function gazeAngles(dir, q, out){
  _gQi.copy(q).invert();
  _gL.copy(dir).applyQuaternion(_gQi);
  out.yaw = Math.atan2(_gL.x, _gL.z) * R2D;
  out.pitch = Math.asin(gClamp(_gL.y, -1, 1)) * R2D;
  return out;
}
const _gAng = { yaw: 0, pitch: 0 }, _gAng2 = { yaw: 0, pitch: 0 };

function setupGaze(){
  if (!['neckLower', 'neckUpper', 'head', GAZE_REF].every(n => bone(n))) return;
  gazeState.bones = ['abdomenUpper', 'chestLower', 'chestUpper',
                     'neckLower', 'neckUpper', 'head', 'lEye', 'rEye']
    .filter(n => bone(n));
  gazeState.anim = gazeState.bones.map(() => new THREE.Quaternion());
  /* Is the eye bone's +Z really the way it looks? The rest of this rig puts
     every bone's tail on +Z (handoff §4) so it should be, but an eye pointing
     out the side of her head is the most obvious thing that can go wrong here.
     Measure it rather than assume. */
  const e = bone('lEye'), hd = bone('head');
  if (e && hd){
    e.getWorldQuaternion(_gQe); hd.getWorldQuaternion(_gQh);
    _gE.set(0, 0, 1).applyQuaternion(_gQe);
    _gF.set(0, 0, 1).applyQuaternion(_gQh);
    gazeState.eyeAxisOk = +(Math.acos(gClamp(_gE.dot(_gF), -1, 1)) * R2D).toFixed(1);
  }
  gazeState.ready = true;
}
/* The one place this block looks at its host's animation state, written to
   shrug if there is nothing there. */
function gazeClipScale(){
  try {
    const n = (typeof current !== 'undefined' && current && current.getClip)
      ? current.getClip().name : null;
    return (n && n in GAZE.byClip) ? GAZE.byClip[n] : 1;
  } catch (e) { return 1; }
}
/* Deciding to look somewhere is not the same as looking there. A decision sets
   a pending target and a reaction beat; the eyes take it immediately and the
   head only when the beat has run out. */
function gazeCommit(yaw, pitch, immediate){
  gazeState.pendYaw = yaw; gazeState.pendPitch = pitch;
  gazeState.pending = true;
  gazeState.reactT = immediate ? 0 : gRand(GAZE.react[0], GAZE.react[1]);
}
function pickAway(){
  const s = Math.random() < 0.5 ? -1 : 1;
  let a = gazeState.camYaw + s * gRand(GAZE.awayMin, GAZE.awayMax);
  a = gClamp(a, -GAZE.yawMax, GAZE.yawMax);
  // if the comfort clamp dragged it back onto you, go the other way instead
  if (Math.abs(a - gazeState.camYaw) < GAZE.awayMin * 0.6)
    a = gClamp(gazeState.camYaw - s * gRand(GAZE.awayMin, GAZE.awayMax),
               -GAZE.yawMax, GAZE.yawMax);
  gazeState.awayYaw = a;
  gazeState.awayPitch = gRand(-11, 13);
  gazeCommit(a, gazeState.awayPitch, false);
}

function applyGaze(dt){
  if (!gazeState.ready) return;
  const h = Math.min(dt, 1 / 20);

  charRoot.updateMatrixWorld(true);
  const ref = bone(GAZE_REF), hd = bone('head');
  ref.getWorldQuaternion(_gQc);
  hd.getWorldPosition(_gP);

  // where you are, in her pelvis frame — the frame that makes "behind her
  // shoulder" mean something, and that this system does not itself rotate
  _gD.subVectors(camera.position, _gP);
  if (_gD.lengthSq() < 1e-8) return;
  _gD.normalize();
  gazeAngles(_gD, _gQc, _gAng);
  gazeState.camYaw = _gAng.yaw;
  gazeState.camPitch = _gAng.pitch;

  // ── decide ──────────────────────────────────────────────────────────────
  const reach = Math.abs(gazeState.camYaw);
  let targetW = 0;
  gazeState.heldFor += h;

  if (!GAZE.on){
    gazeState.mode = 'idle';
  } else if (gazeState.mode === 'idle'){
    if (reach <= GAZE.regain){
      gazeState.mode = 'engaged'; gazeState.sub = 'cam';
      gazeState.t = gRand(GAZE.holdCam[0], GAZE.holdCam[1]);
      gazeCommit(gazeState.camYaw, gazeState.camPitch, false);
      gazeState.heldFor = 0; gazeState.arrived = false;
    }
  } else if (gazeState.mode === 'engaged' && reach > GAZE.giveUp){
    gazeState.mode = 'returning';
    gazeCommit(0, 0, false);
  }

  if (gazeState.mode === 'engaged'){
    gazeState.t -= h;
    if (gazeState.t <= 0){
      if (gazeState.sub === 'cam'){
        gazeState.sub = 'away'; pickAway();
        gazeState.t = gRand(GAZE.holdAway[0], GAZE.holdAway[1]);
      } else {
        gazeState.sub = 'cam';
        gazeState.t = gRand(GAZE.holdCam[0], GAZE.holdCam[1]);
        gazeCommit(gazeState.camYaw, gazeState.camPitch, false);
      }
      gazeState.arrived = false;
      gazeState.heldFor = 0;
    }
    /* Re-acquire, the part that stops this being a tracking camera. She only
       bothers if you have moved appreciably AND she has held the old target a
       while. Small orbits move nothing at all, which is the point. */
    if (gazeState.sub === 'cam' && !gazeState.pending
        && gazeState.heldFor > GAZE.reacquireWait
        && Math.abs(gazeState.camYaw - gazeState.aimYaw) > GAZE.reacquire){
      gazeCommit(gazeState.camYaw, gazeState.camPitch, false);
      gazeState.heldFor = 0;
    }
    /* The expression fires when she ARRIVES on you, not when she decides to
       look. Luca's order — look, then the face, then she turns away — and it is
       the right order: an expression that starts while the head is still moving
       reads as a mask being put on rather than as a reaction to seeing you. */
    if (gazeState.sub === 'cam' && !gazeState.arrived && !gazeState.pending
        && Math.abs(gazeState.curYaw - gazeState.aimYaw) < 6){
      gazeState.arrived = true;
      const cycling = (typeof FACE !== 'undefined') && FACE.cycle;
      if (GAZE.express && !cycling && typeof faceTrigger === 'function'){
        /* Take the hold from the Face panel, shortened only if the look itself
           is shorter. It used to be `min(t*0.75, 3.2)`, which ignored FACE.hold
           entirely — so that slider did nothing at all for the automatic case,
           which is the only case that matters. */
        const lo = (typeof FACE !== 'undefined') ? FACE.hold[0] : 1.1;
        const hi = (typeof FACE !== 'undefined') ? FACE.hold[1] : 2.6;
        const fired = faceTrigger('random', 1,
          Math.min(lo + Math.random() * (hi - lo), gazeState.t * 0.8));
        /* A face and a look are not separable. Sadness shortens the look — she
           drops her eyes — and being hurt lengthens it, because holding your
           gaze is most of what makes it reproachful. The expression says how
           long she stays. */
        if (fired && typeof faceHoldBias === 'function')
          gazeState.t = Math.max(0.8, gazeState.t * faceHoldBias(fired));
      }
    }
    targetW = 1;
  } else if (gazeState.mode === 'returning'){
    // she does not stare at her own shoulder waiting for you: she faces front
    targetW = 1;
    if (Math.abs(gazeState.curYaw) < 3.5 && Math.abs(gazeState.curPitch) < 3.5)
      gazeState.mode = 'idle';
  } else {
    if (!gazeState.pending && (gazeState.aimYaw !== 0 || gazeState.aimPitch !== 0))
      gazeCommit(0, 0, true);
  }

  // the reaction beat, then the head takes the target the eyes already have
  if (gazeState.pending){
    gazeState.reactT -= h;
    if (gazeState.reactT <= 0){
      gazeState.aimYaw = gClamp(gazeState.pendYaw, -GAZE.yawMax, GAZE.yawMax);
      gazeState.aimPitch = gClamp(gazeState.pendPitch, -GAZE.pitchDown, GAZE.pitchUp);
      gazeState.pending = false;
    }
  }

  targetW *= gazeClipScale();

  /* Second-order, not a lag. A lag is fastest at the instant it starts, which
     is precisely the servo read; a spring starts at rest, gathers, and settles.
     Slightly under-damped so it arrives rather than creeps. */
  const w0 = GAZE.ease, z = GAZE.damp;
  gazeState.velYaw   += (w0*w0*(gazeState.aimYaw   - gazeState.curYaw)   - 2*z*w0*gazeState.velYaw)   * h;
  gazeState.velPitch += (w0*w0*(gazeState.aimPitch - gazeState.curPitch) - 2*z*w0*gazeState.velPitch) * h;
  gazeState.curYaw   += gazeState.velYaw * h;
  gazeState.curPitch += gazeState.velPitch * h;
  gazeState.weight += (targetW - gazeState.weight) * (1 - Math.exp(-h * GAZE.weightSpeed));

  // the look-around overlay is her idling; duck it while she is actually
  // looking at something, and hand it back when she is not
  if (typeof addActions !== 'undefined'){
    const la = addActions.get('Add_LookAround');
    if (la) la.setEffectiveWeight(((typeof addBase !== 'undefined'
                                    && addBase.get('Add_LookAround')) ?? 0.88)
                                  * (1 - GAZE.suppress * gazeState.weight));
  }

  const w = gazeState.weight;
  if (w < 1e-3) return;

  // ── apply ───────────────────────────────────────────────────────────────
  for (let i = 0; i < gazeState.bones.length; i++){
    const b = bone(gazeState.bones[i]);
    if (b) gazeState.anim[i].copy(b.quaternion);
  }

  /* How much of this her body takes. Small glances are head-only; past about
     20° the torso starts coming round with her, which is the difference between
     a person turning to look and a head rotating on a mannequin. */
  const need = Math.abs(gazeState.curYaw);
  const u = gClamp((need - GAZE.torsoFrom) / Math.max(1, GAZE.torsoSpan), 0, 1);
  const torso = u * u * (3 - 2 * u) * GAZE.torso;

  gazeDir(gazeState.curYaw, gazeState.curPitch, _gQc, _gD);
  const chain = torso > 0.001
    ? GAZE_TORSO.map(([n, s]) => [n, s * torso]).concat(GAZE_NECK)
    : GAZE_NECK;
  for (const [n, share] of chain){
    const b = bone(n); if (!b) continue;
    // recompute from where the head actually points now: each link has already
    // moved the ones below it, so a single precomputed delta would overshoot
    hd.getWorldQuaternion(_gQh);
    _gF.set(0, 0, 1).applyQuaternion(_gQh);
    _gQd.setFromUnitVectors(_gF, _gD);
    rotateBoneWorld(b, share >= 0.999 ? _gQd : _gQb.copy(IDENT).slerp(_gQd, share));
  }

  /* Eyes last, and on the PENDING target when there is one — so they arrive
     before the head does. They are also allowed past where the neck will go,
     which is what makes her look like she is looking rather than pointing. */
  if (bone('lEye') || bone('rEye')){
    const ty = gazeState.pending ? gazeState.pendYaw : gazeState.aimYaw;
    const tp = gazeState.pending ? gazeState.pendPitch : gazeState.aimPitch;
    gazeDir(ty, tp, _gQc, _gE);
    hd.getWorldQuaternion(_gQh);
    gazeAngles(_gE, _gQh, _gAng2);
    const ke = 1 - Math.exp(-h * GAZE.eyeSpeed);
    gazeState.eyeYaw   += (gClamp(_gAng2.yaw,   -GAZE.eyeYaw,   GAZE.eyeYaw)   - gazeState.eyeYaw)   * ke;
    gazeState.eyePitch += (gClamp(_gAng2.pitch, -GAZE.eyePitch, GAZE.eyePitch) - gazeState.eyePitch) * ke;
    gazeDir(gazeState.eyeYaw, gazeState.eyePitch, _gQh, _gD);
    for (const n of ['lEye', 'rEye']){
      const b = bone(n); if (!b) continue;
      b.getWorldQuaternion(_gQe);
      _gF.set(0, 0, 1).applyQuaternion(_gQe);
      rotateBoneWorld(b, _gQd.setFromUnitVectors(_gF, _gD));
    }
  }

  // blend against the animation the way the grab does: snapshot, solve, slerp
  // back by the weight, so it takes over and hands back without a pop
  for (let i = 0; i < gazeState.bones.length; i++){
    const b = bone(gazeState.bones[i]); if (!b) continue;
    _gQb.copy(b.quaternion);
    b.quaternion.copy(gazeState.anim[i]).slerp(_gQb, w);
  }
  charRoot.updateMatrixWorld(true);
}
/* ══ END PORTABLE BLOCK: gaze ════════════════════════════════════════════════ */

/* ══════ end verbatim ══════ */

  return {
    setup: () => setupGaze(),
    apply: (dt) => {
    current = H.current ? H.current() : null;
      return applyGaze(dt);
    },
    link: (api) => { faceTrigger = api.faceTrigger; faceHoldBias = api.faceHoldBias; faceGazeBias = api.faceGazeBias; twistGazeBias = api.twistGazeBias; FACE = api.FACE; },
    api: { setupGaze, applyGaze, gazeCommit, GAZE, gazeState },
  };
}
