/* GENERATED by pipeline/wrap_blocks.py from hairlab/blocks/hair.js.
   Do not edit here and do not edit the block below: the owning
   session's copy is the source of truth and this file is that source
   wrapped, unchanged. Re-run the script instead. */

export function install(H){
  const { THREE, bone, charRoot } = H;

/* ══════ verbatim: hairlab/blocks/hair.js ══════ */
/* hair.js — extracted from hairlab/index.html by extract_blocks.py.
   Do not edit here; edit index.html and re-run the extractor. */

/* ══ BEGIN PORTABLE BLOCK: hair ══════════════════════════════════════════════
   ───────────────────────── hair ─────────────────────────────────────────────
   Procedural hair on the existing cards. The hair is one skinned node (HAIR,
   nine primitives — eight M_hair plus the M_haircap scalp) welded rigidly to
   the skull, so out of the box every card moves as one solid piece. This does
   not simulate strands — nothing here is per-strand, it is a handful of springs
   on the CPU and a few instructions in the vertex shader on geometry you are
   already paying for — but it is more than a wobble, because one channel alone
   cannot cover what she does.

   THREE CHANNELS, because a single translating spring demonstrably is not enough:

   · swing — the hanging mass lags when the head is moved: dragged by the arm,
     walking, bobbing, nodding. A translation.
   · twist — the mass sweeps around the skull and catches up late when she
     turns. This is the one a translation cannot express at all: a mass hanging
     directly under the yaw axis barely feels a yaw, so before this channel
     existed a 40° head turn moved the hair six millimetres. Measured.
   · tip whip — a second, slower, softer spring that the ends carry far more of
     than the roots (hw³ against hw). Without it the whole length arrives at the
     same time and reads as a board swinging; with it the tips trail the
     mid-lengths and keep moving after they have stopped, which is most of what
     separates hair from a hinged flap.

   DRIVE. Same base-excited oscillator the soft tissue uses, and for the same
   reason: a hanging mass whose support accelerates settles near a/(damping·ω),
   so `gain` is 1.0 because that is what the physics says rather than a number
   dialled until it looked right (brief-hair.md, "gain matters more than
   stiffness"). The pivot is deliberately NOT the head bone's origin — a head
   turn barely moves that point. It is a point held rigidly out from the skull
   at the middle of the hanging mass, which picks up the tangential and
   centripetal terms for free.

   SPACES — the trap on this asset, and the reason every unit-carrying term is
   computed on the CPU and converted through one matrix rather than written into
   the shader. The injection lands after <skinning_vertex>, so its offset passes
   through the model matrix ALONE, and on this asset that space is CENTIMETRES
   and Z-UP (0.01 world metres per unit, object +Z pointing at world −Y). But
   `position`, the attribute the falloff weighs against, is the bind attribute:
   METRES and Y-UP. Both are true at once. Measured either side of skinning the
   ratio is 1.0 and everything looks correct, which is exactly how this hides.
   So: the shader makes no assumption about axes or scale anywhere — it weights
   and adds vectors handed to it — and `toObj()` is the single place the
   conversion happens.                                                        */
const HAIR = {
/* These are Luca's, dialled by eye and pasted back — not defaults I reasoned to.
   Where his choice contradicts what the physics would have picked, his wins;
   the notes just say what he chose so it is not silently re-derived later. */
  on: true, amp: 1.69,
  stiffness: 23,            // ω ≈ 4.8 rad/s — a 0.76 Hz swing. He halved my guess: slower reads heavier
  damping: 2.8,             // ζ ≈ 0.29 — and looser with it, so it keeps travelling
  gain: 1.0,
  max: 0.25,                // he took this to the old ceiling, so the ceiling moved
  axis: [1.0, 0.40, 1.0],   // a card slides sideways and front-to-back; it cannot stretch downward
  tipLag: 1.08,             // how much of the travel the slow tip spring carries — nearly double mine
  tipRatio: 0.37,           // tip spring frequency relative to the main one: 2.7× slower
  tipDamp: 0.72,            // and its damping, relative — looser, so it keeps going
  twist: 2.1,               // master on the twist channel — he doubled it
  twistStiff: 40, twistDamp: 4.2, twistMax: 1.1,   // radians ≈ 63°
  /* 0.98 with a curve of 2.8 is the interesting pair: the root line is almost at
     her crown, so the motion reaches nearly the whole mass, but the steep curve
     keeps the amplitude collected at the ends. A low root line with a shallow
     curve would move the same span far more uniformly, and reads like a wig. */
  rootFrac: 0.98,
  curve: 2.8,
  drift: 0.0155, driftSpeed: 0.57,
  /* 0.3 puts the drive point almost on the head bone, which mostly takes the
     translation channel out and leaves the turn-driven twist to carry the read.
     That is a taste decision and it is his. */
  armScale: 0.3,
  collide: true, collScale: 1.0,
};
/* Four spheres standing in for her head, upper back and shoulders, carried by
   the bones they hang off. Spheres rather than capsules or ellipsoids on
   purpose: a sphere needs no orientation, so the whole test is a subtract, a
   length and a compare, and four of them cover the only places long hair
   actually goes through a body — the back of the skull when it twists, and the
   shoulders and upper back when it swings forward. Offsets are in the bone's
   own frame and are carried with it. */
const HAIR_COLL = [
  { bone: 'head',       off: [0,  0.020, -0.015], r: 0.098 },
  { bone: 'chestUpper', off: [0,  0.055, -0.030], r: 0.140 },
  { bone: 'lShldrBend', off: [-0.02, 0.005, 0],   r: 0.072 },
  { bone: 'rShldrBend', off: [ 0.02, 0.005, 0],   r: 0.072 },
];
/* Uniform objects, shared by every hair material and the depth material, so one
   write per frame drives all ten programs. Everything here is already in the
   shader's own space. */
const hairU = {
  sway:   { value: new THREE.Vector3() },
  swayTip:{ value: new THREE.Vector3() },
  driftA: { value: new THREE.Vector3() },
  driftB: { value: new THREE.Vector3() },
  pivot:  { value: new THREE.Vector3() },
  ax:     { value: new THREE.Vector3(0, 0, 1) },
  twist:  { value: 0 },
  range:  { value: new THREE.Vector2(1.62, 1.25) },
  curve:  { value: 1.55 },
  wave:   { value: new THREE.Vector3(6.2, 4.1, 0) },   // x freq, z freq, time
  coll:   { value: [new THREE.Vector4(), new THREE.Vector4(),
                    new THREE.Vector4(), new THREE.Vector4()] },
};
const hairState = {
  meshes: [], ready: false, init: false, t: 0, unit: 1,
  prev: new THREE.Vector3(), vel: new THREE.Vector3(), acc: new THREE.Vector3(),
  disp: new THREE.Vector3(), dvel: new THREE.Vector3(),
  dispT: new THREE.Vector3(), dvelT: new THREE.Vector3(),
  yaw: 0, yawVel: 0, yawVelPrev: 0, yawAcc: 0,
  armRest: new THREE.Vector3(),
  tw: 0, twVel: 0,
  arm: new THREE.Vector3(), anchor: new THREE.Vector3(),
  tip: 1.25, crown: 1.83, span: 0.58, L: 0.40,
};
/* Own scratch, per the rule that has cost this project the most: a helper that
   borrows another helper's module-level temporary silently produces identity. */
const _hA = new THREE.Vector3(), _hV = new THREE.Vector3(), _hF = new THREE.Vector3();
const _hO = new THREE.Vector3(), _hW = new THREE.Vector3(), _hD = new THREE.Vector3();
const _hQ = new THREE.Quaternion(), _hM3 = new THREE.Matrix3(), _hM4 = new THREE.Matrix4();
const _hC = new THREE.Vector3(), _hQ2 = new THREE.Quaternion();

/* Injected after <skinning_vertex>. Note what is NOT in here: no axis constants,
   no unit conversions, no world-space anything. It weights vectors it is given
   and rotates about an axis it is given. `position` is the untouched bind
   attribute, so the falloff is measured against the rest shape and cannot drift
   as she moves; `transformed` is the skinned position, which is the only thing
   in the right space to rotate about the twist axis. */
const HAIR_CHUNK = `
  float hSpan = max(1e-4, uHairRange.x - uHairRange.y);
  float hw = pow(clamp((uHairRange.x - position.y) / hSpan, 0.0, 1.0), uHairCurve);
  float hph = position.x * uHairWave.x + position.z * uHairWave.y + uHairWave.z;
  vec3 hoff = uHairSway * hw
            + uHairSwayTip * (hw * hw * hw)
            + (uHairDriftA * sin(hph) + uHairDriftB * cos(hph * 0.9)) * hw;
  if (abs(uHairTwist) > 1e-6){
    vec3 hrel = transformed - uHairPivot;
    vec3 hrad = hrel - uHairAxis * dot(hrel, uHairAxis);
    float hth = uHairTwist * hw;
    hoff += hrad * (cos(hth) - 1.0) + cross(uHairAxis, hrad) * sin(hth);
  }
  /* Collision. The trap: these cards already graze her shoulders at rest, so a
     plain push-out would shove the hair off her body the instant the feature
     was enabled and change every pose the modeller approved. hairClamp takes
     the rest position as the allowance instead — see its definition. */
  transformed = hairClamp(transformed + hoff, transformed);
`;
function patchHairShader(shader){
  shader.uniforms.uHairSway    = hairU.sway;
  shader.uniforms.uHairSwayTip = hairU.swayTip;
  shader.uniforms.uHairDriftA  = hairU.driftA;
  shader.uniforms.uHairDriftB  = hairU.driftB;
  shader.uniforms.uHairPivot   = hairU.pivot;
  shader.uniforms.uHairAxis    = hairU.ax;
  shader.uniforms.uHairTwist   = hairU.twist;
  shader.uniforms.uHairRange   = hairU.range;
  shader.uniforms.uHairCurve   = hairU.curve;
  shader.uniforms.uHairWave    = hairU.wave;
  shader.uniforms.uHairColl    = hairU.coll;
  shader.vertexShader = shader.vertexShader
    .replace('#include <common>', `#include <common>
      uniform vec3 uHairSway; uniform vec3 uHairSwayTip;
      uniform vec3 uHairDriftA; uniform vec3 uHairDriftB;
      uniform vec3 uHairPivot; uniform vec3 uHairAxis; uniform float uHairTwist;
      uniform vec2 uHairRange; uniform float uHairCurve; uniform vec3 uHairWave;
      uniform vec4 uHairColl[4];
      /* Keep p out of her body, but never push it further out than where it
         started. r0 is the smaller of the collider radius and how far the REST
         position already was from the centre, so a card that grazes her
         shoulder in the bind pose keeps exactly the clearance the modeller gave
         it, while one swinging inward is stopped at the surface. At zero
         displacement p == p0 and this is identically a no-op — which is the
         property that lets the whole feature be switched on without changing a
         single rest pose. */
      vec3 hairClamp(vec3 p, vec3 p0){
        for (int i = 0; i < 4; i++){
          vec4 C = uHairColl[i];
          if (C.w > 0.0){
            float r0 = min(C.w, length(p0 - C.xyz));
            vec3 d = p - C.xyz;
            float L = length(d);
            if (L < r0 && L > 1e-5) p = C.xyz + d * (r0 / L);
          }
        }
        return p;
      }`)
    .replace('#include <skinning_vertex>', `#include <skinning_vertex>
      { ${HAIR_CHUNK} }`);
}
function applyHairRange(){
  hairU.range.value.set(hairState.tip + hairState.span * HAIR.rootFrac, hairState.tip);
  hairU.curve.value = HAIR.curve;
}
/* world direction → the shader's space. The single place the 0.01 and the axis
   swap are handled; nothing downstream of here knows about either. */
function toObj(v, out){
  return out.copy(v).applyMatrix3(_hM3);
}
/* Called from start(), after the bones are mapped and the subject is framed. */
function setupHair(){
  const want = new Set(['M_hair', 'M_haircap']);
  const lo = new THREE.Vector3(Infinity, Infinity, Infinity);
  const hi = new THREE.Vector3(-Infinity, -Infinity, -Infinity);
  const seen = new Set();
  let base = null;
  charRoot.traverse((o) => {
    if (!o.isMesh && !o.isSkinnedMesh) return;
    const list = Array.isArray(o.material) ? o.material : [o.material];
    const mine = list.filter(m => m && want.has(m.name));
    if (!mine.length) return;
    hairState.meshes.push(o);
    for (const m of mine){
      if (seen.has(m.uuid)) continue;
      seen.add(m.uuid);
      m.onBeforeCompile = patchHairShader;
      m.customProgramCacheKey = () => 'hair-proc';
      m.needsUpdate = true;
      if (m.name === 'M_hair' && !base) base = m;
    }
    const g = o.geometry;
    if (g && g.attributes && g.attributes.position){
      if (!g.boundingBox) g.computeBoundingBox();
      lo.min(g.boundingBox.min); hi.max(g.boundingBox.max);
    }
  });
  if (!hairState.meshes.length || !isFinite(lo.y) || !isFinite(hi.y)) return;

  hairState.tip = lo.y; hairState.crown = hi.y;
  hairState.span = Math.max(0.05, hi.y - lo.y);

  // world metres per unit of the shader's space, measured off the matrix rather
  // than assumed — it is 0.01 here and it will not be on the next asset
  const mw = hairState.meshes[0].matrixWorld.elements;
  hairState.unit = Math.hypot(mw[0], mw[1], mw[2]) || 1;

  // pendulum length, measured: head bone down to the tips, in charRoot space so
  // the subject's framing offset cancels
  const hb = bone('head');
  if (hb){
    hb.getWorldPosition(_hA);
    charRoot.worldToLocal(_hA);
    hairState.L = Math.max(0.15, _hA.y - hairState.tip);
  }

  /* Where the hair's mass actually is. This is the number that decides whether a
     lean does anything: the drive point is carried rigidly by the skull, so if
     it is placed too far down it ends up BELOW the chest pivot, and leaning her
     over swings it one way while translating her head the other. The two then
     very nearly cancel — a 92 mm head move produced 0.49 m/s² where the geometry
     says 4.5, and the hair barely twitched at a lean that should have thrown it.

     So: sample the hair and take the centroid, rather than picking an offset
     that looks about right. Sampling is every 37th vertex — 133k vertices, and
     a centroid converges long before you have counted them all. Expressed in
     the head's own frame, so it is carried correctly however she is posed. */
  if (hb){
    const c = new THREE.Vector3(); let n = 0;
    const tmp = new THREE.Vector3();
    for (const o of hairState.meshes){
      if (!o.isSkinnedMesh || !o.applyBoneTransform) continue;
      const pa = o.geometry.attributes.position;
      for (let i = 0; i < pa.count; i += 37){
        tmp.fromBufferAttribute(pa, i);
        o.applyBoneTransform(i, tmp);
        o.localToWorld(tmp);
        c.add(tmp); n++;
      }
    }
    if (n > 32){
      c.divideScalar(n);
      hb.getWorldPosition(_hA);
      hb.getWorldQuaternion(_hQ);
      hairState.armRest.subVectors(c, _hA).applyQuaternion(_hQ.invert());
      hairState.sampled = n;
    }
  }
  // a sane fallback if the sampling found nothing to work with
  if (hairState.armRest.lengthSq() < 4e-4 || hairState.armRest.length() > 0.6)
    hairState.armRest.set(0, -hairState.span * 0.30, -0.02);
  hairState.arm.copy(hairState.armRest);
  applyHairRange();

  /* The hair casts a shadow onto her shoulders and back, and three.js renders
     that through its own depth material, which knows nothing about the
     injection — so without this the shadow stays rigid under moving hair, which
     is the sort of thing an animator sees before anything else. One depth
     material covers all nine primitives; it takes the M_hair alpha because that
     is eight of them and 130k of the 133k vertices, and the scalp cap it gets
     slightly wrong is underneath the rest of the hair anyway. */
  if (base){
    const dm = new THREE.MeshDepthMaterial({
      depthPacking: THREE.RGBADepthPacking,
      map: base.map, alphaMap: base.alphaMap, alphaTest: base.alphaTest,
    });
    dm.onBeforeCompile = patchHairShader;
    dm.customProgramCacheKey = () => 'hair-proc-depth';
    for (const o of hairState.meshes) o.customDepthMaterial = dm;
    hairState.depth = dm;
  }
  hairState.ready = !!hb;
}
/* Runs last in the frame, after the soft-tissue pass, per brief-hair.md: it
   reads final head world transforms. The tree update at the top is what makes
   "final" true — with no grab active applyGrab returns before it updates, and
   the head matrix would otherwise be a frame stale. */
function applyHair(dt){
  if (!hairState.ready) return;
  const h = Math.min(dt, 1 / 45);
  hairState.t += h * HAIR.driftSpeed;
  hairU.wave.value.z = hairState.t;

  charRoot.updateMatrixWorld(true);
  const mesh = hairState.meshes[0];
  _hM3.setFromMatrix4(mesh.matrixWorld).invert();
  _hM4.copy(mesh.matrixWorld).invert();

  // colliders first, and unconditionally: they are carried by their bones, so
  // they have to be current whatever the springs go on to do
  for (let i = 0; i < HAIR_COLL.length; i++){
    const C = HAIR_COLL[i], cb = bone(C.bone), u = hairU.coll.value[i];
    if (!cb || !HAIR.collide){ u.w = 0; continue; }
    cb.getWorldQuaternion(_hQ2);
    cb.getWorldPosition(_hC);
    _hC.add(_hW.set(C.off[0], C.off[1], C.off[2]).applyQuaternion(_hQ2));
    _hC.applyMatrix4(_hM4);
    u.set(_hC.x, _hC.y, _hC.z, C.r * HAIR.collScale / hairState.unit);
  }

  const hb = bone('head');
  hb.getWorldQuaternion(_hQ);
  hb.getWorldPosition(_hA);
  hairState.arm.copy(hairState.armRest).multiplyScalar(HAIR.armScale);
  hairState.anchor.copy(hairState.arm).applyQuaternion(_hQ).add(_hA);

  /* Her heading, for the twist channel, as the twist half of a swing-twist
     split about world up: yaw = 2·atan2(q.y, q.w). The obvious alternative —
     project the skull's forward vector onto the floor and take an atan2 — is
     ill-conditioned exactly when she looks up or down, because the projection
     shrinks toward zero and its direction then swings on rounding error. It
     read 186 rad/s during the walk, which is 10,000 degrees a second, and
     slammed the twist into its limit on every lap. This form has no such
     degeneracy; it only wraps, and the wrap is unwrapped below. */
  const yaw = 2 * Math.atan2(_hQ.y, _hQ.w);

  if (!hairState.init){
    hairState.prev.copy(hairState.anchor);
    hairState.yaw = yaw; hairState.init = true; return;
  }

  // ── swing driver ────────────────────────────────────────────────────────
  _hV.subVectors(hairState.anchor, hairState.prev).divideScalar(h);
  _hF.subVectors(_hV, hairState.vel).divideScalar(h);
  hairState.prev.copy(hairState.anchor); hairState.vel.copy(_hV);
  // twice-differentiated positions at a variable step are noisy, and a
  // single-frame spike reads as a twitch rather than as hair
  if (_hF.lengthSq() > 900) _hF.setLength(30);
  hairState.acc.lerp(_hF, 1 - Math.exp(-h * 26));

  // ── twist driver ────────────────────────────────────────────────────────
  let dy = yaw - hairState.yaw;
  while (dy >  Math.PI) dy -= 2 * Math.PI;
  while (dy < -Math.PI) dy += 2 * Math.PI;
  hairState.yaw = yaw;
  // smooth the rate before differentiating it. Differentiating twice at a
  // variable timestep is noisy enough on positions; on an angle read off a
  // quaternion it is worse, and a single bad frame becomes a whip-crack.
  let yv = dy / h;
  if (Math.abs(yv) > 25) yv = Math.sign(yv) * 25;   // 1400°/s — no neck does this
  hairState.yawVel += (yv - hairState.yawVel) * (1 - Math.exp(-h * 40));
  let ya = (hairState.yawVel - hairState.yawVelPrev) / h;
  hairState.yawVelPrev = hairState.yawVel;
  if (Math.abs(ya) > 120) ya = Math.sign(ya) * 120;
  hairState.yawAcc += (ya - hairState.yawAcc) * (1 - Math.exp(-h * 26));

  if (!HAIR.on){
    hairU.sway.value.set(0, 0, 0); hairU.swayTip.value.set(0, 0, 0);
    hairU.driftA.value.set(0, 0, 0); hairU.driftB.value.set(0, 0, 0);
    hairU.twist.value = 0;
    return;
  }

  const A = HAIR.axis, g = Math.max(0, HAIR.amp);
  // anisotropic compliance on the forces, isotropic restoring spring — a card
  // slides across her and swings away from her far more readily than it
  // shortens, and applying this to the output instead would bend the spring
  _hD.set(hairState.acc.x * A[0], hairState.acc.y * A[1], hairState.acc.z * A[2])
     .multiplyScalar(-g * HAIR.gain);

  // main spring
  _hO.copy(_hD)
     .addScaledVector(hairState.disp, -HAIR.stiffness)
     .addScaledVector(hairState.dvel, -HAIR.damping);
  hairState.dvel.addScaledVector(_hO, h);
  hairState.disp.addScaledVector(hairState.dvel, h);
  if (hairState.disp.length() > HAIR.max) hairState.disp.setLength(HAIR.max);

  /* Tip spring: same drive, slower and looser, so the ends arrive late and
     leave late. hw³ in the shader is what keeps it off the roots.

     The kT/k factor on the drive is the important part and it was missing. A
     spring's static response to an acceleration is a/ω², so making this one
     slower ALSO made it proportionally bigger — dropping the ratio to 0.37
     multiplied its travel by 7.3 and it then sat on its cap permanently. The
     symptom is exact: every small head turn produced a full-amplitude whip, and
     the whip stopped looking driven by anything, because past saturation it no
     longer was. Normalising by kT/k makes "slowness" mean only slowness: the
     ends still arrive late and leave late, but how FAR they go is Tip whip's
     job alone, and a small motion now gives a small whip. */
  const kT = HAIR.stiffness * HAIR.tipRatio * HAIR.tipRatio;
  const cT = HAIR.damping * HAIR.tipDamp;
  _hO.copy(_hD).multiplyScalar(HAIR.tipLag * (kT / Math.max(1e-4, HAIR.stiffness)))
     .addScaledVector(hairState.dispT, -kT)
     .addScaledVector(hairState.dvelT, -cT);
  hairState.dvelT.addScaledVector(_hO, h);
  hairState.dispT.addScaledVector(hairState.dvelT, h);
  // 0.6, not the full max: these two springs add at the tips, so capping both
  // at the same number would put the real ceiling at twice what the slider says
  if (hairState.dispT.length() > HAIR.max * 0.6) hairState.dispT.setLength(HAIR.max * 0.6);

  // inextensibility, on the CPU where the units are honest: swinging a tip out
  // by d also lifts it by d²/2L, because the card cannot get longer
  _hW.copy(hairState.disp).add(hairState.dispT);
  const lift = (_hW.x * _hW.x + _hW.z * _hW.z) / (2 * hairState.L);
  _hW.copy(hairState.disp); _hW.y += lift * 0.5;
  toObj(_hW, hairU.sway.value);
  _hW.copy(hairState.dispT); _hW.y += lift * 0.5;
  toObj(_hW, hairU.swayTip.value);

  // ── twist ───────────────────────────────────────────────────────────────
  const tAcc = -hairState.yawAcc * g * HAIR.gain;
  const tA = tAcc - HAIR.twistStiff * hairState.tw - HAIR.twistDamp * hairState.twVel;
  hairState.twVel += tA * h;
  hairState.tw += hairState.twVel * h;
  // A generous internal stop, only so the integrator cannot run away.
  if (Math.abs(hairState.tw) > 3) hairState.tw = Math.sign(hairState.tw) * 3;
  // The limit belongs on the OUTPUT. It used to be applied to `tw` and the
  // master multiplied afterwards, so with the master at 2.1 a "63° limit"
  // produced 91° and the slider was quietly lying about what it did.
  let tv = hairState.tw * HAIR.twist;
  if (Math.abs(tv) > HAIR.twistMax) tv = Math.sign(tv) * HAIR.twistMax;
  hairU.twist.value = tv;

  // axis and pivot for that rotation, both converted here so the shader stays
  // free of any assumption about which way is up in its own space
  _hW.set(0, 1, 0);
  toObj(_hW, hairU.ax.value).normalize();
  hairU.pivot.value.copy(_hA).applyMatrix4(_hM4);

  // ── idle drift: a breath of movement so the still frames are not still ──
  const dAmp = HAIR.drift * g;
  _hW.set(dAmp, 0, 0);            toObj(_hW, hairU.driftA.value);
  _hW.set(0, dAmp * 0.25, dAmp);  toObj(_hW, hairU.driftB.value);
}

/* ══ END PORTABLE BLOCK: hair ════════════════════════════════════════════════ */

/* ══════ end verbatim ══════ */

  return {
    setup: () => setupHair(),
    apply: (dt) => applyHair(dt),
    api: { setupHair, applyHair, HAIR },
  };
}
