/* GENERATED by pipeline/wrap_blocks.py from viewer/blocks/mood.js.
   Do not edit here and do not edit the block below: the owning
   session's copy is the source of truth and this file is that source
   wrapped, unchanged. Re-run the script instead. */

export function install(H){
  const { THREE, bone, camera, GRAB, jigState, JIG } = H;
  let softDrag = null;
  let FACE, GAZE, gazeState, TWIST, twistState, BAL, LEG;

/* ══════ verbatim: viewer/blocks/mood.js ══════ */
/* ══ PORTABLE BLOCK: mood ════════════════════════════════════════════════════

   How she feels, what changes it, and what it changes.

   ── why this exists at all ─────────────────────────────────────────────────
   There were TWO mood mechanisms in the build and they did not talk to each
   other. `FACE.mood` named a weight table (warm / playful / reserved /
   melancholy / mixed) and was set once at install and never touched again;
   `MOOD.v/a` in balance.js was a live valence/arousal pair that drifted back to
   a constant. Since the gaze stopped firing `random()`, the named tables were
   very nearly dead code.

   This block replaces both. One system, three timescales:

     1. FEELING      (v, a)         seconds → ~30 s.   What she reacts WITH.
     2. DISPOSITION  a named table  ~2 min.            Where her feeling RESTS.
     3. EASE         one number     ~15 min.           How she is WITH YOU.

   The important structural change is tier 2: the named table is no longer a
   dial, it is a CLASSIFICATION of where her feeling has been sitting, and it
   feeds back by setting the resting point tier 1 decays toward. So "she is in a
   playful mood" is something you can cause rather than something you pick.

   ── the four decisions Luca made ───────────────────────────────────────────
   · **No `restless` table.** Negative-and-ACTIVATED routes to `reserved` — she
     goes quiet on you rather than bristling — and negative-and-QUIET routes to
     `melancholy`. There is no bristling quadrant and there is deliberately no
     route to fear.
   · **She rests warm, and it is asymmetric.** *"I like her kind of default look
     a lot already, so I'm fine for her to rest in that a lot."* The disposition
     average moves toward warm at full rate and away from it at `homeBias` of
     that, so a rough patch has to be sustained to move her and a kind one
     brings her home quickly.
   · **Ease is in.** Tier 3 is what makes the same stroke mean something
     different at minute one and minute ten: it scales how hard good things
     land, how long she will hold your eye, and how far up the touch arc she
     will go at all.
   · **The floor is gone.** `moodFloor` clamped how low she was ever allowed to
     FEEL; it is removed, so a rough session reads. The keep-out list that
     enforces *"we never want her to actually look afraid"* is a separate thing
     and has been narrowed from four expressions to one — `worried`. `sad`,
     `hurt` and `tired` are now reachable, which is the whole point of removing
     the floor; removing it while keeping all four excluded would have changed
     nothing. `MD.keepOut` restores the old list.

   ── the two mechanics that stop it being a lookup table ────────────────────
   **Habituation.** Every event belongs to a fatigue class. Each trigger raises
   that class's fatigue and the nudge is scaled by (1 − fatigue), decaying over
   `fatTau`. Fifty strokes are not fifty times one stroke. This was the single
   biggest thing missing before: every stroke was worth exactly the same.

   **Contrast.** An event is worth more against a background it disagrees with.
   A gentle touch after you have been hauling her about lands much harder than
   the same touch after two calm minutes. One multiplier, and it is most of what
   makes a reaction feel earned.

   ── who owns her face ──────────────────────────────────────────────────────
   This block does, exclusively. At install the viewer switches off
   `BAL.face`, `BAL.touch`, `TWIST.express` and `GAZE.express`, all of which
   used to fire expressions on their own. Balance keeps `balPosture` (her body
   answering her face) and `jawOpen` (a physical reflex, not an expression),
   because neither of those FIRES anything.

   It names no expression except through the catalogue's own coordinates, so a
   twenty-third pose joins in without a line being written here.

   Host contract: THREE, bone, charRoot, camera, GRAB, jigState, JIG, playBase;
   live softDrag, current; linked FACE, GAZE, gazeState, TWIST, twistState,
   BAL, LEG. Everything linked is optional — each use is guarded, so the block
   installs into a build with no balance layer and simply senses less.
*/

const MD = {
  on: true,

  /* ── tier 1: feeling ──────────────────────────────────────────────────── */
  tau: 26,            // seconds for the feeling to return to the disposition
  jitter: 0.16,       // so the same feeling is not the same face twice

  /* ── tier 2: disposition ──────────────────────────────────────────────── */
  slowTau: 110,       // seconds of averaging behind the named table
  hold: 12,           // and how long a new table must win before it switches
  homeBias: 0.45,     // how much more slowly she moves AWAY from warm than back

  /* ── tier 3: ease with you ────────────────────────────────────────────── */
  ease: 1.0,          // master, 0 turns tier 3 off entirely
  easeGain: 0.055,    // how much a good event adds
  easeTau: 900,       // and how long it takes to forget you (15 minutes)

  /* ── the two mechanics ────────────────────────────────────────────────── */
  fatRise: 0.34,      // how much one trigger dulls its own class
  fatTau: 40,         // and how long that lasts, unless FAT_TAU overrides it
  contrast: 0.55,     // how much an event gains from disagreeing with the mood

  /* ── the four dials that reshape the whole event table ────────────────────
     Rather than forty sliders — one per event per axis — the table below is
     data and these are the multipliers over it. Four numbers you can find by
     feel, against a table you can read. */
  warmth: 1.0,        // everything that raises her valence
  rough: 1.0,         // everything that lowers it
  lively: 1.0,        // everything that raises her arousal
  calm: 1.0,          // everything that lowers it

  /* ── firing ───────────────────────────────────────────────────────────── */
  cool: 1.30,         // minimum gap between expressions, so she is not a slideshow
  holdBase: 1.25,     // seconds a one-shot sits before releasing
  keepOut: false,     // true restores the old four-expression exclusion
  touchWait: 0.22,    // contact must last this long before it means anything
  touchStroke: 0.045, // path length of the drag target that counts as a stroke
  touchHold: 2.2,     // how long a touch expression sits while you are there
  touchAfter: 2.6,    // and how long it outlives you letting go
  aloneAfter: 45,     // seconds of nothing at all before she starts to settle
  nearBy: 0.55,       // metres from her head that counts as leaning in

  /* ── what the mood drives besides her face ────────────────────────────────
     Each is a 0…1 authority. At 0 the mood does not touch that system at all,
     which is how you tell whether an effect is earning its place. */
  toGaze: 1.0,        // how long she will hold your eye
  toIdle: 1.0,        // FACE.idle, the micro-drift
  toBalance: 1.0,     // BAL.comfort / BAL.trigger — wound up is twitchier
  toClip: 1.0,        // which idle she drifts into
  show: true,         // the read-out
};

/* Anchors for the named tables, and the routing between them.

   Written as an explicit test rather than a nearest-anchor search, because the
   routing is a DECISION and should be legible as one. Nearest-anchor put
   negative-and-activated in `melancholy`, which is upset; `reserved` is
   withdrawn, and withdrawn is what this figure does. */
const MOOD_ANCHOR = {
  warm:       { v:  0.55, a: 0.25 },
  playful:    { v:  0.70, a: 0.70 },
  reserved:   { v:  0.00, a: 0.35 },
  melancholy: { v: -0.55, a: 0.15 },
  mixed:      { v:  0.20, a: 0.40 },
};
function moodTable(v, a){
  if (v >= 0.15)  return a >= 0.50 ? 'playful' : 'warm';
  if (v <= -0.30) return a >= 0.45 ? 'reserved' : 'melancholy';
  return 'mixed';
}
/* The one she is never allowed to wear, and the old list behind a flag. */
const MOOD_NEVER = ['worried'];
const MOOD_NEVER_ALL = ['worried', 'hurt', 'sad', 'tired'];

/* ── the event table ──────────────────────────────────────────────────────
   `k`: 'i' impulse — a one-off kick, rate-limited by its own fatigue.
        'r' rate    — applied per second while the condition holds.
   `f`: fatigue class. Events sharing a class dull each other, which is what
        makes "keep doing the same thing" stop working. null never dulls.     */
const MOOD_EV = {
  touchContact: { v: +0.08, a: -0.02, k: 'i', f: 'touch' },
  touchStroke:  { v: +0.13, a: -0.04, k: 'i', f: 'touch' },
  touchLong:    { v: +0.20, a: -0.06, k: 'i', f: 'touch' },
  rollHeld:     { v: +0.10, a: +0.15, k: 'r', f: 'roll'  },
  rollRelease:  { v: +0.06, a: -0.08, k: 'i', f: 'roll'  },
  drag:         { v: -0.22, a: +0.55, k: 'r', f: 'drag'  },
  /* Being HELD, as opposed to being hauled. `drag` is keyed on pointer speed,
     which is right — a slow tug is not an event — but it meant that holding her
     arm out at full stretch and simply keeping it there cost her nothing at
     all, indefinitely. probe_mood.py never saw `drag` fire for exactly that
     reason: it set the target once and held it. Quieter than being hauled, and
     it does not stop. */
  held:         { v: -0.05, a: +0.10, k: 'r', f: null    },
  stumble:      { v: -0.30, a: +0.70, k: 'r', f: 'drag'  },
  slip:         { v: -0.05, a: +0.20, k: 'i', f: 'slip'  },
  land:         { v: -0.07, a: +0.28, k: 'i', f: 'land'  },
  footPlaced:   { v: -0.04, a: +0.10, k: 'i', f: 'foot'  },
  settled:      { v: +0.02, a: -0.15, k: 'i', f: 'foot'  },
  unseen:       { v: -0.03, a: -0.05, k: 'r', f: null    },
  found:        { v: +0.05, a: +0.08, k: 'i', f: 'gaze'  },
  heldEye:      { v: +0.09, a: +0.05, k: 'i', f: 'gaze'  },
  alone:        { v: -0.01, a: -0.08, k: 'r', f: null    },
  near:         { v: +0.05, a: +0.12, k: 'i', f: 'near'  },
};

/* Recovery is per class, because the classes do not repeat at the same rate.
   Her eyes arriving on you happens every ten seconds all by itself — at a 40 s
   recovery that one event pumps her valence up faster than being dragged pulls
   it down, and the first run of probe_mood.py measured exactly that: ninety
   seconds of hauling her about left her PLAYFUL. A look is worth something the
   first time and very little the twentieth. */
const MOOD_FAT_TAU = { gaze: 150, near: 120, touch: 40, roll: 45,
                       drag: 25, land: 30, foot: 60, slip: 30 };

const MOODX = {
  ready: false,
  v: 0.38, a: 0.28,                 // tier 1
  sv: 0.55, sa: 0.25,               // tier 2 — the slow average
  table: 'warm', want: 'warm', tableT: 0,
  ease: 0.12,                       // tier 3
  last: '', cool: 0,
  fat: {},                          // habituation, per class
  log: [],                          // the last few events, for the read-out
  trail: [],                        // recent (v, a), for the read-out
  trailT: 0,
  idleT: 0,                         // seconds since anything at all happened
  seenT: 0,                         // seconds she has been unable to see you
};

const _mb = (x) => x < 0 ? 0 : (x > 1 ? 1 : x);
const _mclamp = (x, lo, hi) => x < lo ? lo : (x > hi ? hi : x);

/* ── the one entry point ──────────────────────────────────────────────────
   Everything that happens to her comes through here, so fatigue, contrast and
   ease are applied in exactly one place and cannot be forgotten at a call
   site. `scale` is how much of the event happened — the magnitude of a roll,
   the severity of a landing — and for a rate event it carries the timestep. */
function moodEvent(name, scale){
  const e = MOOD_EV[name];
  if (!e || !MD.on) return 0;
  let s = scale == null ? 1 : scale;
  if (s <= 0) return 0;

  // habituation: the same thing again is worth less
  let fat = 0;
  if (e.f){ fat = MOODX.fat[e.f] || 0; s *= (1 - _mb(fat)); }
  if (s <= 1e-4) return 0;

  /* contrast: how far this event is pushing AGAINST where she already is.
     Something pleasant arriving on a low mood is a bigger event than the same
     thing arriving on a high one, which is the whole reason a rough patch
     makes the next kindness land. */
  const gap = e.v >= 0 ? _mb((0.55 - MOODX.v) / 1.1) : _mb((MOODX.v + 0.55) / 1.1);
  s *= 1 + MD.contrast * gap;

  /* ease: she takes good things better and bad things more lightly the longer
     you have been decent to her */
  const ez = MOODX.ease * MD.ease;
  const dv = e.v * (e.v >= 0 ? MD.warmth * (1 + 0.60 * ez)
                             : MD.rough  * (1 - 0.35 * ez));
  const da = e.a * (e.a >= 0 ? MD.lively : MD.calm);

  /* Soft saturation, not a clamp. A clamp lets one long stroke pin her at
     +1.00 and sit there, which makes every subsequent event invisible and is
     the mood equivalent of the grab bug — shot out and stopped dead. Scaling
     the nudge by the headroom left in the direction it is pushing means she
     approaches the ends and never arrives, so there is always somewhere left
     for the next thing to move her. The same shape as `give()` and the grip
     force, for the same reason. */
  const hv = 1 - Math.abs(dv >= 0 ? Math.max(0, MOODX.v) : Math.min(0, MOODX.v));
  const ha = da >= 0 ? 1 - MOODX.a : MOODX.a;
  MOODX.v = _mclamp(MOODX.v + dv * s * hv, -1, 1);
  MOODX.a = _mclamp(MOODX.a + da * s * Math.max(0.12, ha), 0, 1);

  if (e.f && e.k === 'i') MOODX.fat[e.f] = _mb(fat + MD.fatRise);
  else if (e.f) MOODX.fat[e.f] = _mb(fat + MD.fatRise * s * 0.6);

  // tier 3 only ever rises, and only on things she enjoyed
  if (e.v > 0) MOODX.ease = _mb(MOODX.ease + MD.easeGain * s * e.v * 4);

  /* Rate events go in the log too, coalesced into one row that accumulates
     while they last — otherwise the read-out says nothing at all during the
     loudest thing in the table, and a probe reading the log concludes the event
     never fired. (It did. The first run of probe_mood.py called five of them
     "missed" for exactly this reason.) */
  const head = MOODX.log[0];
  if (e.k === 'r' && head && head.name === name && head.t < 1.5){
    head.v = +(head.v + dv * s * hv).toFixed(3);
    head.a = +(head.a + da * s).toFixed(3);
    head.t = 0;
  } else {
    MOODX.log.unshift({ name, v: +(dv * s * hv).toFixed(3),
                        a: +(da * s).toFixed(3), t: 0, k: e.k });
    if (MOODX.log.length > 7) MOODX.log.pop();
  }
  MOODX.idleT = 0;
  return s;
}

/* ── choosing a face from how she feels ───────────────────────────────────
   No expression is named. `nearest()` asks the catalogue for whatever sits
   closest to (v, a), so the routing survives poses being added. The jitter is
   what stops her being a lookup table: two people in the same mood do not make
   identical faces. */
function moodFeel(scale, hold){
  const F = (typeof window !== 'undefined') && window.Companion && window.Companion.face;
  if (!F || !MD.on) return null;
  const j = MD.jitter;
  const v = _mclamp(MOODX.v + (Math.random() * 2 - 1) * j, -1, 1);
  const a = _mclamp(MOODX.a + (Math.random() * 2 - 1) * j * 0.8, 0, 1);
  const skip = MOODX.last ? [MOODX.last] : [];
  for (const k of (MD.keepOut ? MOOD_NEVER_ALL : MOOD_NEVER)) skip.push(k);
  const id = F.nearest(v, a, { exclude: skip,
                               intensity: scale == null ? 1 : scale, hold });
  if (id){ MOODX.last = id; MOODX.cool = MD.cool; }
  return id;
}

/* ── being touched ────────────────────────────────────────────────────────
   WHERE picks the flavour; WHETHER it is a stroke or a hold is the PATH LENGTH
   of the drag target, not its magnitude — a squeeze moves the flesh a long way
   and goes nowhere, a stroke travels. No gesture recogniser, no velocity
   thresholds.

   What is new here is that the top of the arc is gated on EASE. At low ease a
   long stroke tops out where a short one used to; she has to be comfortable
   with you before the same hand gets the warmer face. That is tier 3 doing
   something you can actually see. */
const MOOD_TOUCH = { region: '', t: 0, path: 0, stage: -1 };
const _mtP = new THREE.Vector3();
const MOOD_KIND = {
  jGluteL: 'pet',   jGluteR: 'pet',
  jThighOL: 'pet',  jThighOR: 'pet',
  jThighIL: 'coy',  jThighIR: 'coy',
  lPectoral: 'coy', rPectoral: 'coy',
  jBelly: 'tickle',
};
/* [on contact, on a short stroke, on a long one] — and a fourth rung that only
   opens once she is easy with you. */
const MOOD_ARC = {
  pet:    ['soft', 'smile', 'amused', 'warmth'],
  coy:    ['soft', 'coy', 'smile', 'pleasure'],
  tickle: ['curious', 'amused', 'grin', 'grin'],
};
function moodTouching(h){
  const F = (typeof window !== 'undefined') && window.Companion && window.Companion.face;
  const held = softDrag || null;
  if (!F || !MD.on){ MOOD_TOUCH.region = ''; return false; }
  if (!held){ MOOD_TOUCH.region = ''; MOOD_TOUCH.stage = -1; return false; }

  const st = (typeof jigState !== 'undefined') ? jigState.get(held) : null;
  if (held !== MOOD_TOUCH.region){
    MOOD_TOUCH.region = held; MOOD_TOUCH.t = 0; MOOD_TOUCH.path = 0;
    MOOD_TOUCH.stage = -1;
    if (st) _mtP.copy(st.target);
  } else if (st){
    MOOD_TOUCH.path += _mtP.distanceTo(st.target);
    _mtP.copy(st.target);
  }
  MOOD_TOUCH.t += h;

  const ez = MOODX.ease * MD.ease;
  const arc = MOOD_ARC[MOOD_KIND[held] || 'pet'];
  const top = ez > 0.55 ? 3 : 2;              // the fourth rung is earned
  const want = MOOD_TOUCH.t < MD.touchWait ? -1
             : MOOD_TOUCH.path > MD.touchStroke * 4.5 ? Math.min(top, 3)
             : MOOD_TOUCH.path > MD.touchStroke * 2.4 ? Math.min(top, 2)
             : MOOD_TOUCH.path > MD.touchStroke ? 1 : 0;

  if (want > MOOD_TOUCH.stage){
    MOOD_TOUCH.stage = want;
    const got = moodEvent(want >= 2 ? 'touchLong'
                        : want === 1 ? 'touchStroke' : 'touchContact', 1);
    /* The per-region arc still wins — where you are touching her is specific in
       a way two numbers cannot be — but its STRENGTH follows how she feels
       about it, and a region with no entry falls through to the mood. */
    const id = arc && arc[want];
    const hold = MD.touchHold + MD.touchAfter;
    if (id) {
      F.play(id, { intensity: (0.45 + 0.20 * want + 0.25 * _mb(MOODX.v)) * (0.55 + 0.45 * (got || 0.2)),
                   hold });
      MOODX.last = id; MOODX.cool = MD.cool;
    } else {
      moodFeel(0.6 + 0.2 * want, hold);
    }
  }
  return true;
}

/* ── everything else that happens to her ──────────────────────────────────
   One pass, reading live state off the other blocks. Every read is guarded:
   with no balance layer in the build this senses touch, the roll and the gaze
   and nothing else, rather than throwing. */
const MOOD_S = { catch: 0, roll: false, rollMag: 0, arrived: false, held: false,
                 placed: [false, false], weight: 0, travel: 0, near: false };
const _mHead = new THREE.Vector3();
function moodSense(h){
  const hasBal = (typeof BAL !== 'undefined') && BAL;
  const hasTw  = (typeof twistState !== 'undefined') && twistState;
  const hasGz  = (typeof gazeState !== 'undefined') && gazeState;

  /* being hauled about — a rate, because a slow tug is not an event but it
     does wind her up */
  if (GRAB.chain && GRAB.releaseT < 0 && hasBal){
    moodEvent('drag', BAL.urgency * h);
    // and the standing cost of being held out there, by how far she has been
    // pulled rather than by how fast — `drive` is 0 inside the dead zone
    moodEvent('held', BAL.drive * h);
  }

  /* Turning her by the sternum. The twist block used to fire the pleasure
     ladder itself and leave no trace at all, which made the most deliberate
     thing you can do to her the only one she did not remember. It is fired
     from here now, so it habituates and it moves her. */
  if (hasTw && typeof TWIST !== 'undefined'){
    const mag = _mb(Math.abs(twistState.twist || 0) / Math.max(1e-4, TWIST.max));
    if (twistState.dragging && mag > 0.15){
      moodEvent('rollHeld', mag * h);
      MOOD_S.rollMag = Math.max(MOOD_S.rollMag, mag);
      if (MOODX.cool <= 0 && mag > 0.35){
        const F = window.Companion && window.Companion.face;
        if (F){ F.ladder('pleasure', mag * (0.5 + 0.5 * MOODX.ease),
                         { intensity: 0.5 + 0.5 * _mb(MOODX.v), hold: 1.4 });
                MOODX.cool = MD.cool; }
      }
    }
    if (MOOD_S.roll && !twistState.dragging && MOOD_S.rollMag > 0.2){
      moodEvent('rollRelease', MOOD_S.rollMag);
      MOOD_S.rollMag = 0;
    }
    MOOD_S.roll = !!twistState.dragging;
  }

  if (hasBal){
    /* Off balance — the strongest negative in the table.

       Keyed on `margin`, the distance her centre of mass has left inside the
       polygon under her feet, and NOT on `BAL.stumbling`: that only rises in
       the Balance-2 preset (`BAL.bold`), which is off here, so keying it there
       made the loudest row in the table unreachable in the default build. A
       negative margin means her mass is outside her own footprint, which is
       what being off balance IS, in both builds. */
    const off = BAL.margin < 0 ? _mb(-BAL.margin / 0.05)
              : (BAL.stumbling > 0.05 ? BAL.stumbling : 0);
    if (off > 0) moodEvent('stumble', off * h);

    // a landing she had to catch, on the rising edge
    if (BAL.catch > 0.25 && MOOD_S.catch <= 0.25) moodEvent('land', _mb(BAL.catch));
    MOOD_S.catch = BAL.catch;

    // you picked up a foot and put it somewhere
    if (typeof LEG !== 'undefined' && LEG) for (let i = 0; i < LEG.length; i++){
      const p = !!LEG[i].placed;
      if (p && !MOOD_S.placed[i]) moodEvent('footPlaced', 1);
      MOOD_S.placed[i] = p;
    }

    /* walked somewhere and came to rest — resolution reads as relief, and it
       is the one positive the balance layer can produce on its own */
    if (MOOD_S.weight > 0.5 && BAL.weight < 0.05 && BAL.travel - MOOD_S.travel > 0.05){
      moodEvent('settled', 1);
      MOOD_S.travel = BAL.travel;
    }
    if (BAL.weight > MOOD_S.weight || BAL.weight < 0.05) MOOD_S.weight = BAL.weight;
    if (BAL.travel < MOOD_S.travel) MOOD_S.travel = BAL.travel;
  }

  if (hasGz && gazeState.ready && typeof GAZE !== 'undefined'){
    // her eyes arriving on you
    const arrived = !!gazeState.arrived;
    if (arrived && !MOOD_S.arrived){
      moodEvent('found', 1);
      if (MOODX.cool <= 0)
        moodFeel(0.75 + 0.25 * MOODX.a,
                 Math.min(MD.holdBase * 2.4, Math.max(1, gazeState.t * 0.8)));
    }
    MOOD_S.arrived = arrived;

    // and holding it, which is a different thing from finding it
    const long = gazeState.sub === 'cam' && gazeState.heldFor > 6;
    if (long && !MOOD_S.held) moodEvent('heldEye', 1);
    MOOD_S.held = long;

    /* orbited round behind her shoulder so meeting your eye would mean
       wringing her neck. She gives up, and going unseen drifts her quiet. */
    const blind = Math.abs(gazeState.camYaw || 0) > (GAZE.giveUp || 84);
    MOODX.seenT = blind ? MOODX.seenT + h : 0;
    if (MOODX.seenT > 4) moodEvent('unseen', h);
  }

  /* you leaned in. Once per approach, with hysteresis, or a camera that sits
     near her face would trigger it every frame. */
  const hd = bone('head');
  if (hd && camera){
    hd.getWorldPosition(_mHead);
    const d = camera.position.distanceTo(_mHead);
    if (!MOOD_S.near && d < MD.nearBy){ moodEvent('near', 1); MOOD_S.near = true; }
    else if (MOOD_S.near && d > MD.nearBy * 1.6) MOOD_S.near = false;
  }

  /* and you went away. Not souring — settling: arousal falls a long way and
     valence barely moves, which is a person left alone rather than a person
     being neglected. */
  MOODX.idleT += h;
  if (MOODX.idleT > MD.aloneAfter) moodEvent('alone', h);
}

/* ── the disposition, and everything the mood drives ─────────────────────── */
function moodDrive(h){
  /* tier 2. The slow average moves at full rate toward warm and at `homeBias`
     of that away from it — Luca's *"I'm fine for her to rest in that a lot"*
     as one line of code rather than as a comment. */
  const home = MOOD_ANCHOR.warm;
  /* `away` means the feeling is pulling the average further from warm than it
     already is. Named for the direction it describes: the first version called
     this `toward` and meant the opposite, which is precisely the kind of thing
     that survives review and then behaves backwards for a month. */
  const away = Math.abs(MOODX.v - home.v) > Math.abs(MOODX.sv - home.v);
  const drift = MD.slowTau * (away ? 1 / Math.max(0.05, 1 - MD.homeBias) : 1);
  const kSlow = 1 - Math.exp(-h / Math.max(1, drift));
  MOODX.sv += (MOODX.v - MOODX.sv) * kSlow;
  MOODX.sa += (MOODX.a - MOODX.sa) * kSlow;

  /* and the table it names, with hysteresis: a candidate has to keep winning
     for `hold` seconds, or she flickers between two tables at a boundary */
  const want = moodTable(MOODX.sv, MOODX.sa);
  if (want === MOODX.table){ MOODX.want = want; MOODX.tableT = 0; }
  else if (want === MOODX.want){
    MOODX.tableT += h;
    if (MOODX.tableT >= MD.hold){ MOODX.table = want; MOODX.tableT = 0; }
  } else { MOODX.want = want; MOODX.tableT = 0; }

  // tier 1 returns to wherever tier 2 now says she lives
  const A = MOOD_ANCHOR[MOODX.table] || MOOD_ANCHOR.warm;
  /* The same asymmetry on the fast clock. Whichever table she is classified
     into, coming back UP toward warm is quicker than sinking away from it, so a
     kindness after a rough patch reads immediately and a rough patch has to
     keep being rough. */
  const up = A.v >= MOODX.v;
  const kv = 1 - Math.exp(-h / Math.max(0.5, MD.tau * (up ? 1 - MD.homeBias * 0.5 : 1)));
  const ka = 1 - Math.exp(-h / Math.max(0.5, MD.tau));
  MOODX.v += (A.v - MOODX.v) * kv;
  MOODX.a += (A.a - MOODX.a) * ka;

  // tier 3 forgets you slowly
  MOODX.ease = _mb(MOODX.ease * Math.exp(-h / Math.max(10, MD.easeTau)));

  // habituation decays
  for (const c in MOODX.fat){
    MOODX.fat[c] *= Math.exp(-h / Math.max(1, MOOD_FAT_TAU[c] || MD.fatTau));
    if (MOODX.fat[c] < 1e-3) delete MOODX.fat[c];
  }
  for (const r of MOODX.log) r.t += h;
  MOODX.cool = Math.max(0, MOODX.cool - h);

  /* ── what the mood drives besides her face ────────────────────────────────
     A mood that only picks an expression is a face-picker. These are all
     existing parameters of other systems; each is behind its own authority so
     you can tell whether it is earning its place. */
  const ez = MOODX.ease * MD.ease;

  if (typeof FACE !== 'undefined' && FACE){
    // the named table and the melancholy blend now follow the disposition
    FACE.mood = MOODX.table;
    FACE.melancholy = MOODX.table === 'melancholy' ? 0.35 : 0.05;
    if (MD.toIdle > 0 && FACE._idle0 == null) FACE._idle0 = FACE.idle;
    if (MD.toIdle > 0)
      FACE.idle = FACE._idle0 * (1 + MD.toIdle * (0.55 * MOODX.a - 0.25));
  }

  if (MD.toGaze > 0 && typeof GAZE !== 'undefined' && GAZE && GAZE.holdCam){
    /* She looks at you longer when she is warm and easy with you, and less
       when she has gone quiet. Written on a remembered baseline so the panel's
       own Gaze sliders stay the thing that sets the range. */
    if (!GAZE._hold0) GAZE._hold0 = [GAZE.holdCam[0], GAZE.holdCam[1],
                                     GAZE.holdAway[0], GAZE.holdAway[1]];
    const w = 1 + MD.toGaze * (0.45 * MOODX.v + 0.35 * ez);
    GAZE.holdCam[0] = GAZE._hold0[0] * w;
    GAZE.holdCam[1] = GAZE._hold0[1] * w;
    GAZE.holdAway[0] = GAZE._hold0[2] / Math.max(0.4, w);
    GAZE.holdAway[1] = GAZE._hold0[3] / Math.max(0.4, w);
  }

  if (MD.toBalance > 0 && typeof BAL !== 'undefined' && BAL){
    // wound up is twitchier: less lean tolerated, a lower step trigger
    if (!BAL._mood0) BAL._mood0 = { comfort: BAL.comfort, trigger: BAL.trigger };
    const t = MD.toBalance * (MOODX.a - 0.3);
    BAL.comfort = BAL._mood0.comfort * _mclamp(1 - 0.45 * t, 0.5, 1.5);
    BAL.trigger = BAL._mood0.trigger * _mclamp(1 - 0.40 * t, 0.5, 1.5);
    // and the resting point balance's own (now dormant) mood would use
    BAL.moodV = A.v; BAL.moodA = A.a;
  }

  if (MD.toIdle > 0 && typeof JIG !== 'undefined' && JIG){
    if (!JIG._damp0) JIG._damp0 = JIG.damping;
    JIG.damping = JIG._damp0 * (1 + 0.18 * MD.toIdle * (MOODX.a - 0.3));
  }

  // the read-out's trail
  MOODX.trailT += h;
  if (MOODX.trailT > 0.35){
    MOODX.trailT = 0;
    MOODX.trail.push([MOODX.v, MOODX.a]);
    if (MOODX.trail.length > 90) MOODX.trail.shift();
  }
}

/* Which idle she drifts into. The shuffle used to pick uniformly at random;
   `Idle_Shy`, `Idle_Sway` and `Idle_Belly` are dispositions already, so let the
   disposition choose. Returns a name from the pool it was handed, so a clip
   that does not exist in this build simply never comes up. */
const MOOD_CLIP = {
  warm:       { Idle_Sway: 3, Idle_Shy: 2, Idle_HairTouch: 2, Idle_Sides: 1.5, Idle_Belly: 1 },
  playful:    { Idle_Sway: 3, Idle_HairTouch: 2.5, Idle_Belly: 2, Idle_Shy: 1, Idle_Sides: 1 },
  reserved:   { Idle_Shy: 4, Idle_Sides: 3, Idle_Belly: 1.5, Idle_Sway: 1, Idle_HairTouch: 0.8 },
  melancholy: { Idle_Shy: 4, Idle_Sides: 2.5, Idle_Belly: 2, Idle_Sway: 0.6, Idle_HairTouch: 0.6 },
  mixed:      { Idle_Shy: 2, Idle_Sides: 2, Idle_Sway: 2, Idle_Belly: 2, Idle_HairTouch: 2 },
};
function moodClip(pool){
  if (!pool || !pool.length) return null;
  if (!(MD.toClip > 0) || !MD.on) return pool[(Math.random() * pool.length) | 0];
  const W = MOOD_CLIP[MOODX.table] || MOOD_CLIP.mixed;
  let total = 0;
  const w = pool.map(n => { const x = Math.pow(W[n] == null ? 1 : W[n], MD.toClip);
                            total += x; return x; });
  let r = Math.random() * total;
  for (let i = 0; i < pool.length; i++){ r -= w[i]; if (r <= 0) return pool[i]; }
  return pool[pool.length - 1];
}

/* ── the read-out ─────────────────────────────────────────────────────────
   Luca: *"let's make it visible for right now so I can track it easier."* The
   feeling as a dot on the valence/arousal plane with a fading trail, the slow
   average as a ring, the routing boundaries drawn where they actually are, and
   below it the disposition, the ease bar and what each fatigue class is
   currently swallowing. Drawn straight to a canvas each frame — cheap, and it
   is the only way to tune this by eye rather than by faith. */
let moodCv = null, moodCtx = null;
function moodCanvas(el){ moodCv = el; moodCtx = el ? el.getContext('2d') : null; }
function moodDraw(){
  if (!moodCtx || !moodCv || !MD.show) return;
  const c = moodCtx, W = moodCv.width, H = moodCv.height;
  const P = 18, w = W - P * 2, hgt = H - P * 2;
  const X = (v) => P + (v + 1) * 0.5 * w;
  const Y = (a) => P + (1 - a) * hgt;

  c.clearRect(0, 0, W, H);
  c.fillStyle = 'rgba(255,255,255,0.035)'; c.fillRect(P, P, w, hgt);

  // the routing boundaries, where they actually are
  c.strokeStyle = 'rgba(255,255,255,0.10)'; c.lineWidth = 1;
  c.beginPath();
  c.moveTo(X(0.15), P); c.lineTo(X(0.15), P + hgt);
  c.moveTo(X(-0.30), P); c.lineTo(X(-0.30), P + hgt);
  c.moveTo(X(0.15), Y(0.50)); c.lineTo(P + w, Y(0.50));
  c.moveTo(P, Y(0.45)); c.lineTo(X(-0.30), Y(0.45));
  c.stroke();

  c.font = '9px ui-monospace, monospace'; c.textAlign = 'center';
  const lab = (t, v, a) => { c.fillStyle = 'rgba(255,255,255,0.28)'; c.fillText(t, X(v), Y(a)); };
  lab('warm', 0.60, 0.22); lab('playful', 0.60, 0.74);
  lab('reserved', -0.65, 0.72); lab('melancholy', -0.65, 0.18); lab('mixed', -0.08, 0.47);

  c.textAlign = 'left';
  c.fillStyle = 'rgba(255,255,255,0.30)';
  c.fillText('valence →', P, H - 5);
  c.save(); c.translate(9, P + hgt); c.rotate(-Math.PI / 2);
  c.fillText('arousal →', 0, 0); c.restore();

  // the trail
  for (let i = 0; i < MOODX.trail.length; i++){
    const t = i / Math.max(1, MOODX.trail.length - 1);
    c.fillStyle = 'rgba(214,166,120,' + (0.05 + 0.30 * t).toFixed(3) + ')';
    c.beginPath(); c.arc(X(MOODX.trail[i][0]), Y(MOODX.trail[i][1]), 1.6, 0, 6.284); c.fill();
  }
  // the slow average
  c.strokeStyle = 'rgba(255,255,255,0.45)'; c.lineWidth = 1.5;
  c.beginPath(); c.arc(X(MOODX.sv), Y(MOODX.sa), 7, 0, 6.284); c.stroke();
  // and how she feels right now
  c.fillStyle = '#d6a678';
  c.beginPath(); c.arc(X(MOODX.v), Y(MOODX.a), 4.5, 0, 6.284); c.fill();
}
function moodReadout(){
  const F = (typeof window !== 'undefined') && window.Companion && window.Companion.face;
  const cur = F ? F.current() : null;
  const fats = Object.keys(MOODX.fat).sort()
    .map(k => k + ' ' + Math.round(MOODX.fat[k] * 100) + '%').join('  ');
  return {
    line1: MOODX.table.toUpperCase()
         + (MOODX.want !== MOODX.table ? '  → ' + MOODX.want
            + ' (' + Math.max(0, MD.hold - MOODX.tableT).toFixed(0) + 's)' : '')
         + '   v ' + MOODX.v.toFixed(2) + '   a ' + MOODX.a.toFixed(2),
    line2: 'ease ' + Math.round(MOODX.ease * 100) + '%'
         + '   face ' + (cur ? cur.id : '—')
         + (MOODX.idleT > MD.aloneAfter ? '   alone ' + MOODX.idleT.toFixed(0) + 's' : ''),
    line3: fats ? 'dulled: ' + fats : 'dulled: —',
    log: MOODX.log.map(r => r.t.toFixed(0) + 's  ' + r.name
                       + '  ' + (r.v >= 0 ? '+' : '') + r.v.toFixed(2)
                       + ' / ' + (r.a >= 0 ? '+' : '') + r.a.toFixed(2)),
  };
}

function setupMood(){
  MOODX.v = MOOD_ANCHOR.warm.v; MOODX.a = MOOD_ANCHOR.warm.a;
  MOODX.sv = MOODX.v; MOODX.sa = MOODX.a;
  MOODX.ready = true;
  return true;
}

function applyMood(dt){
  if (!MOODX.ready || !MD.on) return;
  const h = Math.min(dt, 1 / 20);
  /* Touch runs first and it outranks everything on her FACE: being stroked is
     the one thing that should always be allowed to speak over whatever else is
     happening (it sets MOODX.cool, which every other trigger respects). The
     rest of the world is still sensed while you hold her — she can be stroked
     and stumble in the same second, and both should count. */
  moodTouching(h);
  moodSense(h);
  moodDrive(h);
  moodDraw();
}

/* ══ END PORTABLE BLOCK: mood ═══════════════════════════════════════════════ */

/* ══════ end verbatim ══════ */

  return {
    setup: () => setupMood(),
    apply: (dt) => {
    softDrag = H.softDrag ? H.softDrag() : null;
      return applyMood(dt);
    },
    link: (api) => { FACE = api.FACE; GAZE = api.GAZE; gazeState = api.gazeState; TWIST = api.TWIST; twistState = api.twistState; BAL = api.BAL; LEG = api.LEG; },
    api: { MD, MOODX, MOOD_EV, MOOD_ANCHOR, moodTable, moodEvent, moodFeel, moodClip, moodCanvas, moodDraw, moodReadout, setupMood, applyMood },
  };
}
