/* GENERATED by pipeline/wrap_blocks.py from hairlab/blocks/twist.js.
   Do not edit here and do not edit the block below: the owning
   session's copy is the source of truth and this file is that source
   wrapped, unchanged. Re-run the script instead. */

export function install(H){
  const { THREE, bone, charRoot, camera, canvas, rotateBoneWorld, aimBone, IDENT } = H;

/* ══════ verbatim: hairlab/blocks/twist.js ══════ */
/* twist.js — extracted from hairlab/index.html by extract_blocks.py.
   Do not edit here; edit index.html and re-run the extractor. */

/* ══ BEGIN PORTABLE BLOCK: twist ═════════════════════════════════════════════
   ─────────────────── torso roll ─────────────────────────────────────────────
   ── LIFT-OUT NOTE ─────────────────────────────────────────────────────────
   Needs from its host: bone(name), rotateBoneWorld(b, qWorld), aimBone(b, child,
   target), IDENT, charRoot, camera, canvas, THREE. Call setupTwist() once after the bones are mapped,
   applyTwist(dt) in slot three BEFORE the gaze, and hand it pointer events —
   twistPick(ray) to score, twistDown / twistMove / twistUp to drive. It
   attaches Companion.twist, calls Companion.face.ladder() if that exists, and
   offers twistGazeBias() for the gaze block to read. All optional links are
   guarded; none of them are required.
   ──────────────────────────────────────────────────────────────────────────

   Grab her sternum and drag. Drag sideways and her ribcage turns about her
   spine; drag up or down and it tips back or curls forward; drag in a circle
   and the whole thing circumducts — her chest describes a cone. Her shoulders
   carry most of it, her hips take a little, her knees soften, her feet stay
   where they are.

   FOUR THINGS ARE WORTH KNOWING BEFORE CHANGING ANY OF IT.

   1. THE ANGLE IS DISTRIBUTED, NOT APPLIED TO ONE BONE. Rotating chestUpper
      alone puts the whole turn in one joint and leaves her waist dead — the
      head-on-a-stick failure the gaze had before the torso joined in. A power
      curve over the chain gives every link a share, so the movement spirals up
      her and the shoulders end up with the full angle because they inherit
      everyone else's. The heights each link sits at are SAMPLED from the bones
      at setup, so the profile is right on any rig rather than tuned to this one.

   2. THE HIPS TURN AND THE FEET DO NOT, AND THE RIG MAKES THAT EASY. `pelvis`
      and `abdomenLower` are SIBLINGS under `hip`: the legs hang off one, the
      spine off the other. So `hips` worth of the rotation goes on `hip` — which
      turns her whole body including her legs — and is then cancelled at both
      thighs, which puts everything below the hip joint back where it was. Her
      pelvis turns; her feet never know.

   3. THE HEAD IS NOT ROTATED HERE. The gaze already pins it to you, and
      anything written to the head would simply be cancelled by it a moment
      later. Instead this offers twistGazeBias(), and the gaze adds it to its own
      TARGET — so her head drifts with the roll through the gaze's own spring,
      which is slow and smooth, instead of being dragged by a second system.
      That is the whole reason it looks smooth rather than mechanical.

   4. THE DRAG IS TANGENTIAL, NOT SCREEN-X. A horizontal drag means "push this
      point sideways", and which way that turns her depends on where the camera
      is. The tangential direction at the sternum is projected into screen space
      once at grab time and the drag measured along that, so orbiting round
      behind her does not invert the control under your hand.                  */
const TWIST = {
  on: true,
  max: 26 * Math.PI / 180,     // axial ceiling — the side-to-side turn
  bendMax: 15 * Math.PI / 180, // and the lean, front-back and side-side
  gain: 0.0022,                // radians per pixel of drag
  /* THE DRAG IS AXIAL ONLY, and that is a decision, not a limitation. The cone
     is all still here — `set`, `roll`, and both sliders reach it — but coupling
     it to the drag made her whole torso pivot rather than twist, and took her
     head along with it. Turn these up to put the lean back under your hand. */
  lateral: 0,                  // how much a sideways drag also LEANS her, not just turns her
  sagittal: 0,                 // and how much a vertical drag arches or curls her
  focus: 1.6,                  // how far up the spine the movement concentrates
  hips: 0.22,                  // share taken off the spine and given to her pelvis
  knee: 1.0, kneeMax: 12 * Math.PI / 180,  // knee bend at full lean — she settles by roughly a centimetre
  headFollow: 0.12,            // how much her gaze target drifts with the roll
  ease: 13.0, damp: 1.0,       // while you hold it
  releaseEase: 9.0, releaseDamp: 0.30,   // and on release: swings back past centre
  express: true, expressAt: 0.35,        // a smile once the roll is worth smiling about
  /* The handle is a SEGMENT down her sternum, not a sphere, and that is the
     whole difference between it working and not. Her pectoral pick points sit
     only 8 cm either side with a 10.5 cm radius, so anywhere between her
     breasts — exactly where a hand goes for a sternum — a breast is nearer than
     the centre of any sphere small enough not to steal breast grabs. A segment
     is tall and thin, which is the shape a sternum actually is; its endpoints
     come off the measured midline surface. `pickBias` then tips close calls in
     the centre strip toward it. */
  pickR: 0.055,
  pickA: [0, 0.020, 0.100],    // sternal notch, in chestUpper's frame
  pickB: [0, -0.145, 0.117],   // xiphoid
  pickBias: 0.78,
};
const TWIST_CHAIN = ['abdomenLower', 'abdomenUpper', 'chestLower', 'chestUpper'];
const TWIST_LEGS = [['lThighBend', 'lShin', 'lFoot'], ['rThighBend', 'rShin', 'rFoot']];
const twistState = {
  ready: false, dragging: false,
  twist: 0, lean: 0, bow: 0,            // axial, side-lean, front-back
  vT: 0, vL: 0, vB: 0,
  tT: 0, tL: 0, tB: 0,                  // targets
  atT: 0, atL: 0, atB: 0,               // values at the moment of grab
  startX: 0, startY: 0, dirX: 1, dirY: 0, upX: 0, upY: -1,
  share: [], firedAt: 0,
  base: [], applied: [], legBase: [], legApplied: [],
  legRef: [], legRefQ: [], legLen: [],    // where each foot was, and the two bone lengths above it
  hipBasePos: new THREE.Vector3(), hipAppliedPos: new THREE.Vector3(), sink: 0,
};
/* Own scratch — the rule §4 of the handoff pays for repeatedly. */
const _tP = new THREE.Vector3(), _tA = new THREE.Vector3(), _tR = new THREE.Vector3();
const _tT = new THREE.Vector3(), _tS = new THREE.Vector3(), _tF = new THREE.Vector3();
const _tU = new THREE.Vector3(), _tD = new THREE.Vector3();
const _tQ = new THREE.Quaternion(), _tQa = new THREE.Quaternion();
const _tQb = new THREE.Quaternion(), _tQc = new THREE.Quaternion();
const _tQf = new THREE.Quaternion(), _tQs = new THREE.Quaternion();
const _tE0 = new THREE.Vector3(), _tE1 = new THREE.Vector3(), _tSeg = new THREE.Vector3();
const _tSa = new THREE.Vector3(), _tSb = new THREE.Vector3();
const _tV1 = new THREE.Vector3(), _tV2 = new THREE.Vector3();
const _tQg = new THREE.Quaternion();

function setupTwist(){
  if (!TWIST_CHAIN.every(n => bone(n)) || !bone('hip')) return false;
  for (let i = 0; i <= TWIST_CHAIN.length; i++){       // +1 for `hip`
    twistState.base.push(new THREE.Quaternion());
    twistState.applied.push(new THREE.Quaternion());
  }
  for (const leg of TWIST_LEGS){
    for (const n of leg){
      twistState.legBase.push(new THREE.Quaternion());
      twistState.legApplied.push(new THREE.Quaternion());
    }
    twistState.legRef.push(new THREE.Vector3());
    twistState.legRefQ.push(new THREE.Quaternion());
    twistState.legLen.push({ a: 0, b: 0 });
  }
  twistShares();
  twistState.ready = true;
  return true;
}
/* Share of the total per link, from where each bone actually sits along the
   spine, normalised so the top of the chain always ends up with the full angle
   however the profile is shaped — `focus` moves the movement up or down her
   without changing how far her shoulders go. `hips` is then taken off the top
   of that and handed to her pelvis. */
function twistShares(){
  const hip = bone('hip'), top = bone(TWIST_CHAIN[TWIST_CHAIN.length - 1]);
  hip.getWorldPosition(_tP); top.getWorldPosition(_tA);
  const span = Math.max(1e-4, _tA.distanceTo(_tP));
  const raw = TWIST_CHAIN.map(n => {
    bone(n).getWorldPosition(_tT);
    return Math.pow(Math.min(1, Math.max(0, _tT.distanceTo(_tP) / span)), TWIST.focus);
  });
  const sum = raw.reduce((a, b) => a + b, 0) || 1;
  const h = Math.min(0.6, Math.max(0, TWIST.hips));
  twistState.share = raw.map(v => (v / sum) * (1 - h));
  twistState.hipShare = h;
}
const _tEnds = () => {
  const cu = bone('chestUpper');
  if (!cu) return false;
  cu.getWorldQuaternion(_tQ); cu.getWorldPosition(_tP);
  _tE0.set(TWIST.pickA[0], TWIST.pickA[1], TWIST.pickA[2]).applyQuaternion(_tQ).add(_tP);
  _tE1.set(TWIST.pickB[0], TWIST.pickB[1], TWIST.pickB[2]).applyQuaternion(_tQ).add(_tP);
  return true;
};
function twistEnds(){ return _tEnds(); }
function twistPoint(out){
  if (!_tEnds()) return out.set(0, 0, 0);
  return out.copy(_tE0).add(_tE1).multiplyScalar(0.5);
}
function twistPick(ray){
  if (!TWIST.on || !twistState.ready || !_tEnds()) return Infinity;
  return (Math.sqrt(ray.distanceSqToSegment(_tE0, _tE1, null, _tSeg)) / TWIST.pickR)
         * TWIST.pickBias;
}
/* Her own frame at the spine, measured rather than assumed — she is not always
   standing, and rolling about the wrong axis in a lying pose shears her.
   up = along the spine · fwd = the way her chest faces · side = up × fwd. */
function twistFrame(){
  bone('abdomenLower').getWorldPosition(_tP);
  bone('chestUpper').getWorldPosition(_tA);
  _tU.subVectors(_tA, _tP);
  if (_tU.lengthSq() < 1e-8) _tU.set(0, 1, 0); else _tU.normalize();
  bone('chestUpper').getWorldQuaternion(_tQ);
  _tF.set(0, 0, 1).applyQuaternion(_tQ);
  _tF.addScaledVector(_tU, -_tF.dot(_tU));
  if (_tF.lengthSq() < 1e-8) _tF.set(0, 0, 1); else _tF.normalize();
  _tS.crossVectors(_tU, _tF).normalize();
}
/* Soft limit with a KNEE, not a tanh. A tanh compresses from zero, so a drag
   that should give 25° gave 19 and the whole range felt lazy; this is linear
   until 60% of the ceiling and only then eases in, so you get what you drag
   until you are actually near the limit — and it still asymptotes rather than
   hitting a wall. Same shape solveArm uses near full extension. */
function twistSoft(x, m){
  const knee = m * 0.6, span = Math.max(1e-4, m - knee);
  const a = Math.abs(x);
  const out = a <= knee ? a : knee + span * (1 - Math.exp(-(a - knee) / span));
  return x < 0 ? -out : out;
}
function twistDown(ev){
  if (!twistState.ready) return false;
  twistFrame();
  twistPoint(_tP);
  bone('chestUpper').getWorldPosition(_tA);
  // the radial arm out to the sternum, axial part removed, then the direction
  // that point travels for a positive turn
  _tR.subVectors(_tP, _tA);
  _tR.addScaledVector(_tU, -_tR.dot(_tU));
  if (_tR.lengthSq() < 1e-8) _tR.copy(_tF);
  _tT.crossVectors(_tU, _tR).normalize();

  // project the tangent, and her own up, into screen space once at grab time
  const r = canvas.getBoundingClientRect();
  const o = _tSa.copy(_tP).project(camera);
  const a = _tSb.copy(_tP).addScaledVector(_tT, 0.06).project(camera);
  let dx = (a.x - o.x) * r.width * 0.5, dy = -(a.y - o.y) * r.height * 0.5;
  let L = Math.hypot(dx, dy);
  if (L < 1e-4){ dx = 1; dy = 0; } else { dx /= L; dy /= L; }
  twistState.dirX = dx; twistState.dirY = dy;

  const b = _tSb.copy(_tP).addScaledVector(_tU, 0.06).project(camera);
  let ux = (b.x - o.x) * r.width * 0.5, uy = -(b.y - o.y) * r.height * 0.5;
  L = Math.hypot(ux, uy);
  if (L < 1e-4){ ux = 0; uy = -1; } else { ux /= L; uy /= L; }
  twistState.upX = ux; twistState.upY = uy;

  twistState.dragging = true;
  twistState.startX = ev.clientX; twistState.startY = ev.clientY;
  twistState.atT = twistState.twist; twistState.atL = twistState.lean;
  twistState.atB = twistState.bow;
  twistState.firedAt = 0;
  return true;
}
function twistMove(ev){
  if (!twistState.dragging) return;
  const px = ev.clientX - twistState.startX, py = ev.clientY - twistState.startY;
  // the drag, resolved onto her own two screen directions
  const along = px * twistState.dirX + py * twistState.dirY;
  const up    = px * twistState.upX  + py * twistState.upY;

  twistState.tT = twistSoft(twistState.atT + along * TWIST.gain, TWIST.max);
  twistState.tL = twistSoft(twistState.atL + along * TWIST.gain * TWIST.lateral, TWIST.bendMax);
  twistState.tB = twistSoft(twistState.atB + up * TWIST.gain * TWIST.sagittal, TWIST.bendMax);

  /* A smile, once the roll is worth smiling about. Fired from the TARGET rather
     than the current angle so it lands as she starts moving rather than after
     she arrives, and rate-limited — an expression retriggered every frame never
     gets to rise. */
  if (TWIST.express && typeof window !== 'undefined'
      && window.Companion && window.Companion.face){
    const t = Math.min(1, Math.hypot(twistState.tT / TWIST.max,
                                     twistState.tL / TWIST.bendMax,
                                     twistState.tB / TWIST.bendMax));
    const now = (typeof performance !== 'undefined' ? performance.now() : Date.now()) / 1000;
    if (t > TWIST.expressAt && now - twistState.firedAt > 1.6){
      twistState.firedAt = now;
      window.Companion.face.ladder('pleasure', Math.min(0.95, t));
    }
  }
}
function twistUp(){
  if (!twistState.dragging) return;
  twistState.dragging = false;
  twistState.tT = 0; twistState.tL = 0; twistState.tB = 0;
}
/* What the roll wants the gaze to do — read by the gaze block, not pushed. Her
   head drifting a little with her body is carried by the gaze's own spring,
   which is slow and smooth; rotating her head from here would only be cancelled
   by the gaze a moment later, and would look driven rather than natural. */
const _tBias = { yaw: 0, pitch: 0 };
function twistGazeBias(){
  const k = TWIST.headFollow * 180 / Math.PI;
  _tBias.yaw = twistState.twist * k;
  _tBias.pitch = twistState.bow * k * 0.7;
  return _tBias;
}
function applyTwist(dt){
  if (!twistState.ready) return;
  const h = Math.min(dt, 1 / 30);
  const w0 = twistState.dragging ? TWIST.ease : TWIST.releaseEase;
  const z  = twistState.dragging ? TWIST.damp : TWIST.releaseDamp;
  const spring = (v, x, tgt) => v + (w0 * w0 * (tgt - x) - 2 * z * w0 * v) * h;

  twistState.vT = spring(twistState.vT, twistState.twist, twistState.tT);
  twistState.vL = spring(twistState.vL, twistState.lean,  twistState.tL);
  twistState.vB = spring(twistState.vB, twistState.bow,   twistState.tB);
  twistState.twist += twistState.vT * h;
  twistState.lean  += twistState.vL * h;
  twistState.bow   += twistState.vB * h;
  if (!TWIST.on){
    twistState.twist = twistState.lean = twistState.bow = 0;
    twistState.vT = twistState.vL = twistState.vB = 0;
    twistState.tT = twistState.tL = twistState.tB = 0;
  }

  /* Restore before applying. The mixer rewrites these bones every frame while a
     clip plays, so writing on top of it is safe — but with playback paused
     nothing resets them and the rotation would compound every frame into a
     corkscrew. If a bone still holds exactly what this wrote last frame, the
     mixer did not touch it and the pre-roll value goes back first. */
  const eq = (q, p) => Math.abs(q.x-p.x) < 1e-7 && Math.abs(q.y-p.y) < 1e-7
                    && Math.abs(q.z-p.z) < 1e-7 && Math.abs(q.w-p.w) < 1e-7;
  const names = ['hip'].concat(TWIST_CHAIN);
  for (let i = 0; i < names.length; i++){
    const b = bone(names[i]); if (!b) continue;
    if (eq(b.quaternion, twistState.applied[i])) b.quaternion.copy(twistState.base[i]);
    twistState.base[i].copy(b.quaternion);
  }
  let li = 0;
  for (const leg of TWIST_LEGS) for (const n of leg){
    const b = bone(n); if (!b){ li++; continue; }
    if (eq(b.quaternion, twistState.legApplied[li])) b.quaternion.copy(twistState.legBase[li]);
    twistState.legBase[li].copy(b.quaternion);
    li++;
  }
  // and the same for her hip's POSITION, which the settle below moves
  const hipB = bone('hip');
  if (hipB){
    if (hipB.position.equals(twistState.hipAppliedPos)) hipB.position.copy(twistState.hipBasePos);
    twistState.hipBasePos.copy(hipB.position);
  }

  const mag = Math.abs(twistState.twist) + Math.abs(twistState.lean) + Math.abs(twistState.bow);
  if (mag < 2e-5){
    for (let i = 0; i < names.length; i++) twistState.applied[i].copy(twistState.base[i]);
    for (let i = 0; i < twistState.legBase.length; i++)
      twistState.legApplied[i].copy(twistState.legBase[i]);
    if (hipB) twistState.hipAppliedPos.copy(hipB.position);
    twistState.sink = 0;
    return;
  }

  charRoot.updateMatrixWorld(true);
  twistFrame();

  /* Her feet, before anything moves: wherever the clip has just put them is
     where they have to still be when this is done. The two bone lengths above
     each ankle come off the same pose, so the solve below never assumes her
     proportions. */
  for (let s = 0; s < TWIST_LEGS.length; s++){
    const th = bone(TWIST_LEGS[s][0]), sh = bone(TWIST_LEGS[s][1]), ft = bone(TWIST_LEGS[s][2]);
    if (!th || !sh || !ft) continue;
    ft.getWorldPosition(twistState.legRef[s]);
    ft.getWorldQuaternion(twistState.legRefQ[s]);
    th.getWorldPosition(_tV1); sh.getWorldPosition(_tV2);
    twistState.legLen[s].a = _tV1.distanceTo(_tV2);
    twistState.legLen[s].b = _tV2.distanceTo(twistState.legRef[s]);
  }
  // the full rotation at her shoulders, as one quaternion: turn, then lean,
  // then arch. Composing and slerping from identity per link keeps the three
  // channels consistent with each other at every share.
  _tQa.setFromAxisAngle(_tU, twistState.twist);
  _tQb.setFromAxisAngle(_tF, -twistState.lean);
  _tQc.setFromAxisAngle(_tS, -twistState.bow);
  _tQf.copy(_tQa).multiply(_tQb).multiply(_tQc);

  // her pelvis first — this turns her legs too, and the thighs undo it below
  if (hipB && twistState.hipShare > 0.0005)
    rotateBoneWorld(hipB, _tQs.copy(IDENT).slerp(_tQf, twistState.hipShare));
  twistState.applied[0].copy(hipB ? hipB.quaternion : twistState.base[0]);

  /* Then she settles. A knee that bends shortens the leg, so if her feet are
     staying put her hips have to come down — that drop IS the knee bend, and
     driving it from this end is what keeps the feet planted. The distance is
     the shortening a `kneeMax` bend causes on a leg of her proportions. */
  const _L = twistState.legLen[0];
  const beta = TWIST.knee * TWIST.kneeMax
             * Math.min(1, Math.hypot(twistState.lean, twistState.bow) / TWIST.bendMax);
  twistState.sink = (_L.a && _L.b)
    ? (_L.a + _L.b) - Math.sqrt(_L.a*_L.a + _L.b*_L.b + 2*_L.a*_L.b*Math.cos(beta)) : 0;
  if (hipB && twistState.sink > 1e-6){
    hipB.getWorldPosition(_tV1);
    _tV1.addScaledVector(_tU, -twistState.sink);
    hipB.parent.worldToLocal(_tV1);
    hipB.position.copy(_tV1);
    hipB.updateMatrixWorld(true);
  }
  if (hipB) twistState.hipAppliedPos.copy(hipB.position);

  for (let i = 0; i < TWIST_CHAIN.length; i++){
    const b = bone(TWIST_CHAIN[i]); if (!b) continue;
    rotateBoneWorld(b, _tQs.copy(IDENT).slerp(_tQf, twistState.share[i] || 0));
    twistState.applied[i + 1].copy(b.quaternion);
  }

  /* Legs, solved rather than posed. The ankle is the fixed point: each thigh
     first gives back the pelvis turn, then the knee takes exactly the bend that
     brings that foot back within reach of its moved hip socket, the thigh aims
     the ankle onto its mark, and the ankle's world orientation is put back so
     the sole stays flat. Posing a fixed knee angle instead is what slid her
     feet: the leg gets shorter when it bends, and the amount depends on where
     the hip has gone, so there is no constant that works. Because the pelvis
     rolls, one socket rises and the other drops, and the two knees come out
     bending by different amounts on their own — no side-of-the-lean fudge. */
  _tQb.copy(IDENT).slerp(_tQf, twistState.hipShare).invert();
  const kneeAng = (x, L) => Math.acos(Math.min(1, Math.max(-1,
                    (x*x - L.a*L.a - L.b*L.b) / (2 * L.a * L.b))));
  li = 0;
  for (let s = 0; s < TWIST_LEGS.length; s++){
    const leg = TWIST_LEGS[s];
    const th = bone(leg[0]), sh = bone(leg[1]), ft = bone(leg[2]);
    if (!th || !sh || !ft){ li += 3; continue; }
    const A0 = twistState.legRef[s], L = twistState.legLen[s];
    rotateBoneWorld(th, _tQb);                       // pelvis turn given back

    if (L.a > 1e-5 && L.b > 1e-5){
      const lo = Math.abs(L.a - L.b) + 1e-4, hi = L.a + L.b - 1e-4;
      const clamp = x => Math.min(hi, Math.max(lo, x));
      th.getWorldPosition(_tV1);
      ft.getWorldPosition(_tV2);
      // + about her side axis bends the knee, heel backwards
      const db = kneeAng(clamp(_tV1.distanceTo(A0)), L)
               - kneeAng(clamp(_tV1.distanceTo(_tV2)), L);
      if (Math.abs(db) > 1e-5) rotateBoneWorld(sh, _tQs.setFromAxisAngle(_tS, db));
      aimBone(th, ft, A0);
      ft.getWorldQuaternion(_tQg);
      rotateBoneWorld(ft, _tQs.copy(twistState.legRefQ[s]).multiply(_tQg.invert()));
    }
    twistState.legApplied[li++].copy(th.quaternion);
    twistState.legApplied[li++].copy(sh.quaternion);
    twistState.legApplied[li++].copy(ft.quaternion);
  }
  charRoot.updateMatrixWorld(true);
}

/* ── public API ──────────────────────────────────────────────────────────── */
(function(){
  const C = (window.Companion = window.Companion || { version: 1 });
  const D2R = Math.PI / 180, R2D = 180 / Math.PI;
  C.twist = {
    /* Degrees. `turn` is the axial side-to-side, `lean` tips her sideways,
       `bow` arches her back or curls her forward. Soft-limited the same way a
       drag is, so a caller cannot push her past the limit either. */
    set(turn, lean, bow){
      twistState.tT = twistSoft((turn || 0) * D2R, TWIST.max);
      twistState.tL = twistSoft((lean || 0) * D2R, TWIST.bendMax);
      twistState.tB = twistSoft((bow  || 0) * D2R, TWIST.bendMax);
      twistState.dragging = false;
      return this.get();
    },
    /* Somewhere on the cone, by angle: 0° tips her forward, 90° to her left.
       roll(t) around a full turn is the circumduction. */
    roll(deg, amount){
      const a = (deg || 0) * D2R, m = Math.min(1, Math.max(0, amount == null ? 1 : amount));
      return this.set((Math.sin(a) * m * TWIST.max) * R2D,
                      (Math.sin(a) * m * TWIST.bendMax * TWIST.lateral) * R2D,
                      (Math.cos(a) * m * TWIST.bendMax) * R2D);
    },
    /* A flick: set it and let go, so it swings through and settles. This is the
       one to call when something happens TO her. */
    nudge(turn, lean, bow, hold){
      this.set(turn, lean, bow);
      setTimeout(() => { twistState.tT = twistState.tL = twistState.tB = 0; },
                 Math.max(0, hold == null ? 0.12 : hold) * 1000);
      return this.get();
    },
    release(){ twistState.tT = twistState.tL = twistState.tB = 0; twistState.dragging = false; },
    get(){ return { turn: +(twistState.twist * R2D).toFixed(2),
                    lean: +(twistState.lean  * R2D).toFixed(2),
                    bow:  +(twistState.bow   * R2D).toFixed(2),
                    sink: +(twistState.sink * 1000).toFixed(1),   // mm she has settled
                    dragging: twistState.dragging }; },
    get shares(){
      const out = { hip: +(twistState.hipShare || 0).toFixed(3) };
      TWIST_CHAIN.forEach((n, i) => { out[n] = +(twistState.share[i] || 0).toFixed(3); });
      return out;
    },
    set focus(v){ TWIST.focus = v; twistShares(); },
    get focus(){ return TWIST.focus; },
    set hips(v){ TWIST.hips = v; twistShares(); },
    get hips(){ return TWIST.hips; },
    settings(){ return Object.assign({}, TWIST, {
      max: +(TWIST.max * R2D).toFixed(1), bendMax: +(TWIST.bendMax * R2D).toFixed(1),
      kneeMax: +(TWIST.kneeMax * R2D).toFixed(1) }); },
  };
})();
/* ══ END PORTABLE BLOCK: twist ═══════════════════════════════════════════════ */

/* ══════ end verbatim ══════ */

  return {
    setup: () => setupTwist(),
    apply: (dt) => applyTwist(dt),
    api: { setupTwist, applyTwist, twistPick, twistDown, twistMove, twistUp, twistGazeBias, twistState, TWIST },
  };
}
